Hotfix - API - Error provocado por las cadenas vacías
SinergiaTIC/SinergiaDA pull request #105
Opened 2024-02-07 12:51 UTC by jortilles

## Descripción del Cambio
Cuando una consulta devuelve un campo vacío o nulo EDA devolvía una cadena vacía.  ''.  Como resultado de una actualización ahora esa cadena vacía provoca un error en los componentes de visualización. Por lo que se ha cambiado la cadena vacía '' por una cadena que contiene un espacio en blanco ' ' 

## Issue(s) resuelto(s)

- solves  #101 
- solves  #104
- solves #58 

## Pruebas a realizar para validar el cambio
Realizar un test  para cada caso.
1. Tabla con datos con cadenas en blanco.
2. Graficos de barras normales
3. Graficos de barras apliladas.

2024-02-07 13:41 UTC, juanSTIC requested changes
Los cambios introducidos en el PR provocan que algunas cosas hayan dejado de funcionar, por ejemplo un informe básico de Personas que incluya los campos 
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/8e235e6f-6037-4e72-b025-fdc2bbf75b4e)
provoca un error si contiene campos vacíos (o nulos?), sin embargo funciona correctamente si añado un filtro que quite los campos vacíos
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/29509e7c-6a96-4fa3-af9b-66aa70aa6316)

2024-02-07 15:35 UTC, PaulaaSTIC requested changes
El issue #101 sigue ocurriendo

2024-02-07 17:26 UTC, juanSTIC requested changes
Aparentemente el issues #58 y el issue #104 han quedado resueltos, 
sin embargo los issues #101 y #96 que son los que afectan a la visualización de las tablas siguen exactamente igual

2024-02-07 20:29 UTC, jortilles commented
Puede ser que el problema es porque tienes la consulta en cache?
Yo si que observo el comportamiento correcto.
<img width="608" alt="image" src="https://github.com/SinergiaTIC/SinergiaDA/assets/1340212/cb90e986-10ba-4400-91d7-49ee180fc87e">
Prueba a cambiar algo en la consulta para evitar la cache.

2024-02-08 05:27 UTC, jortilles commented
Con el commit que acabo de hacer se debería soluconar también la #96  
El algoritomo para evitar duplicados estaba causando este problema. Lo pongo todo en la misma rama porque todo debe ir junto.

2024-02-08 07:02 UTC, juanSTIC requested changes
He hecho las siguientes acciones, y en todos los casos se ha seguido provocando el error #101 :
- He descargado mi rama local
- He reiniciado la API
- He modificado la consulta, variando los datos, cambiando el nombre de columna
- He comprobado que en el modelo la cache está desactivada, aun así he hecho click en Borrar cache
- He rehecho el informes desde 0

2024-02-08 11:09 UTC, juanSTIC commented
Se cierra el PR. Los Issues #96 y #101 quedan corregidos en el PR #106 de manera aislada.

2024-02-08 11:09 UTC, closed without merging