Enhancement -  APP - Sda#91 -Protección de usuarios necesarios para SinergiaDA
SinergiaTIC/SinergiaDA pull request #112
Opened 2024-02-15 17:05 UTC by jortilles

## Descripción del Cambio
Se añade la posibilidad de que ciertos registros estén deshabilitados.

## Issue(s) resuelto(s)
- solves  https://github.com/SinergiaTIC/SinergiaDA/issues/91 

## Pruebas a realizar para validar el cambio
Revisar la tabla que lista los usuarios y comprobar que no se pueden eliminar los usuarios técnicos.
Revisar la tabla que lista los grupos y comprobar que no se pueden eliminar los grupos técnicos.

2024-02-19 07:24 UTC, juanSTIC reviewed
@jortilles,  El grupo_SDA_BASIC_ no queda protegido. Según he visto, es porque en cada instancias tiene un id diferente, aunque aún no es un problema, pensando en el futuro ¿podría deshabilitarse también?

2024-02-21 10:49 UTC, juanSTIC commented
Pendiente, en update model crear el grupo SDA_BASIC con un id fijo y proteger la edición de ese grupo mediante el ID

2024-03-04 07:24 UTC, juanSTIC requested changes
En el PR aparecen conflictos pendientes de resolver, que en caso de que no se resuelvan harán que vuelva a aparecer el bug de los valores repetidos en tablas

2024-05-03 10:57 UTC, PaulaaSTIC approved these changes
Aprobado, se protegen los grupos EDA_ADMIN, EDA_RO, EDA_DATASOURCE_CREATOR y los usuarios: eda@sinergiada.org y edaanonim@jortilles.com.

2024-05-06 07:18 UTC, juanSTIC approved these changes

2024-05-06 07:18 UTC, merged