Improvement APP+API  Permitir filtrar "vacío" a nivel informe SDA#126
SinergiaTIC/SinergiaDA pull request #120
Opened 2024-02-28 06:11 UTC by jortilles

## Descripción del Cambio
Se cambia el comportamiento para que se permita filtrar "vacio" a nivell de informe.
SE ESTABLECE UN VAOR POR DEFECTO PARA LOS NULOS. que hemos inicializado a 'null'
CABE DESTACAR QUE UN VALOR NULO Y UNA CADENA VACIA '' SON VALORES DISTINTOS. Nosotros tratamos los nulos.  

## Issue(s) resuelto(s)
- solves https://github.com/SinergiaTIC/Sinergia-Data-Analytics/issues/126
- solves https://github.com/SinergiaTIC/SinergiaDA/issues/58
- solves https://github.com/SinergiaTIC/SinergiaDA/issues/56
- solves https://github.com/SinergiaTIC/SinergiaDA/issues/147
## Pruebas a realizar para validar el cambio
Realizar un informe donde haya paneles con valores nulos y comprobar el funcionamiento.
Hacer un informe con varios filtros sobre una misma columna
Hacer un iforme con varios filtros sobre una columna. Uno de los cuales debe ser el valor nulo.

## Información Adicional
Este PR entra en conflicto con https://github.com/SinergiaTIC/SinergiaDA/pull/119  Debe integrarse despues que ese

2024-03-01 10:32 UTC, juanSTIC commented
Se valora que el nuevo valor Null y los elementos vacíos aparezcan juntos y al principio el filtro

2024-04-29 11:20 UTC, PaulaaSTIC requested changes
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/94ba6ed1-2b08-45b3-b8c9-bb9545c2998c)
El issue [#126](https://github.com/SinergiaTIC/Sinergia-Data-Analytics/issues/126) no se ha solucionado. Se ha incluido el filtrado de nulos a nivel de informe, pero no de "vacío" como está a nivel de panel.

2024-04-30 05:29 UTC, jortilles commented
Hola. @PaulaaSTIC 
Puedes ser un poco más específica en la explicación de las pruebas.
Yo lo he probado con el campo convenio de acciones sepe y me funciona bien.
<img width="686" alt="image" src="https://github.com/SinergiaTIC/SinergiaDA/assets/1340212/947c6fa1-5973-4b31-9c1f-2d505f99ce6b">

2024-04-30 07:43 UTC, PaulaaSTIC submitted a review, later dismissed
(A)probado

2024-05-10 08:50 UTC, jortilles commented
Añadir dos opciones más "excluir nulos y vacíos "  "incluir nulos y vacios" a nivel de filtro de panel

2024-05-31 13:27 UTC, asafJortilles commented
@jortilles actualizado con nuevos filtros.

2024-06-03 05:42 UTC, jortilles commented
Ya se puede volver a probar este PR.
Este PR resuelve también https://github.com/SinergiaTIC/SinergiaDA/issues/147

2024-06-03 10:09 UTC, juanSTIC requested changes
Además de los comentarios incluidos se ha visto que no aplica el modo árbol y que no se muestra las rutas de aplicación de los filtros en la configuración del panel.

2024-06-04 13:45 UTC, closed without merging