Feature  -  APP+API +  Mejora - EDA - Permitir gestión de múltiples relaciones entre tablas SDA#53
SinergiaTIC/SinergiaDA pull request #140
Opened 2024-04-10 15:33 UTC by jortilles

## Descripción del Cambio
Refactor para poder definir el camino que debe seguri SinergiaDA para hacer las relaciones

## Issue(s) resuelto(s)
- solves  https://github.com/SinergiaTIC/SinergiaDA/issues/53 

## Pruebas a realizar para validar el cambio
Realizar un informe nuevo y comprobar las consultas que se hacen.

- Realizar un panel con diferentes columnas.
- Realizar varios paneles
- Realizar filtros

2024-04-15 16:23 UTC, PaulaaSTIC commented
Una vez desplegado el árbol, hay algunas relaciones donde la etiqueta aparece repetida. 
![Screenshot from 2024-04-15 17-53-17](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/5f43ebac-2747-45de-bef0-c784836aefd7)

Si el módulo principal es igual a  `source_table`, la etiqueta debería ser el módulo de la izquierda. En caso de que el módulo principal sea igual a `target_table`,  debería ser la derecha. Actualmente, para las relaciones con `source_table`, el proceso se realiza correctamente, pero es necesario corregir el otro caso.


![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/d169b4a3-9308-4afb-b024-9b794172a86a)

2024-04-15 16:34 UTC, PaulaaSTIC commented
En los filtros a nivel de informe, no puedo deseleccionar un panel para que no se aplique el filtrado.

![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/f09a89cb-5aac-46e2-aa38-c21f9a318998)

2024-04-15 16:55 UTC, PaulaaSTIC commented
Con los filtros a nivel panel me está ocurriendo lo siguiente:

1. Tengo un panel de eventos y otro de inscripciones. Cuando añado un filtro al panel de eventos y luego intento guardar sin elegir registros para filtrar (dejando el filtro vacío), no me permite guardar y aparece el siguiente error. Incluso si lleno el filtro, tampoco puedo guardarlo.

![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/d5229d60-34fc-4213-9b57-fe475359f175)
2. Cuando selecciono valores para filtrar en el filtro y se aplica correctamente a los paneles del módulo del filtro, pero en el panel relacionado salta el siguiente error:
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/91bb8355-f143-45fe-80aa-df553221fd49) 
Si edito la consulta, obtengo lo siguiente:
```
SELECT cast(sum(`sda_stic_registrations`.`N`) as decimal(32,0) ) as `(n) Inscripciones`  
FROM sda_stic_registrations 
inner JOIN `sda_stic_events` ON  `sda_stic_registrations`.`stic_registrations_stic_eventsstic_events_ida` = `sda_stic_events`.`id`  
where  `sda_stic_events`.`id`  in (1,2,3,4) 

```
Esta consulta, si la ejecuto en la base de datos, me devuelve un resultado correcto. Sin embargo, en el informe, el proceso se queda pensando y no muestra nada.

2024-04-15 16:56 UTC, PaulaaSTIC requested changes
Comentarios en la conversación

2024-04-16 08:21 UTC, juanSTIC commented
**Se pierde el último campos añadido en el modo árbol**
Al guardar un panel con campos de módulos diferentes, se ha perdido el último campo al guardar, o no se ha guardado, o no se carga al recargar el informe
![Peek 2024-04-16 10-19](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/389c81b0-9f2d-4166-b310-60d292b07a44)

2024-04-16 08:27 UTC, juanSTIC commented
**El filtrado de campos deja de funcionar en algunas circunstancias**
Se ha visto que frecuentemente, aunque no siempre, solamente funciona el filtrado de campos en el primer nivel del árbol. En los siguientes deja de funcionar y se muestra un error de javascript como puede verse en la consola.
![Peek 2024-04-16 10-26](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/a0e2ba38-fa58-4ace-850e-1e8453318638)

2024-04-16 08:29 UTC, juanSTIC requested changes
Se han encontrado los siguientes errores que son bloqueantes:
- https://github.com/SinergiaTIC/SinergiaDA/pull/140#issuecomment-2058518004
- https://github.com/SinergiaTIC/SinergiaDA/pull/140#issuecomment-2058528721

2024-04-16 08:35 UTC, juanSTIC commented
**Al añadir una columna al panel, se contrae el árbol**, lo que dificulta la usabilidad, aunque el módulo seleccionado sigue siendo el mismo que se acaba de usar, el árbol debería mantenerse manteniendo el foco en el mismo sitio

2024-04-17 07:07 UTC, juanSTIC requested changes
Ver comentarios

2024-04-17 09:35 UTC, juanSTIC commented
Se ha perdido las opciones de visibilidad de los filtros (solo lectura, estc...) a nivel de informe

2024-04-17 09:49 UTC, jortilles commented on eda/eda_api/lib/module/datasource/datasource.controller.ts
> +/* SDA CUSTOM */    if (e._id != "111111111111111111111111") {
Listo!

2024-04-17 09:55 UTC, jortilles commented on eda/eda_api/package.json
> -        "mariadb": "^3.1.2",
Rstaurado MariaDB

2024-04-17 09:57 UTC, jortilles commented on eda/eda_app/src/app/module/components/eda-panels/eda-blank-panel/panel-charts/panel-chart.component.ts
> +        if (this.componentRef && !['table', 'crosstable'].includes(this.props.chartType)) {
Error que hemos resuelto por el camino. Los componentes 'table' y  'crosstable' no tiene el componente updateChart() por eso se han cambiado.

2024-04-17 12:00 UTC, PaulaaSTIC commented
**Comportamiento erróneo al arrastrar un campo.**
Cuando intentamos incluir un campo que en el modo oculto tiene otros campos encima, observamos un comportamiento diferente dependiendo de si arrastramos el campo o si simplemente hacemos clic sobre él para incluirlo en el panel. Si lo arrastramos, se añade el campo que esté en la posición del que deseamos en la versión del modo oculto.


![error_arrastre_campo](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/c30eb658-ae5d-45f9-9c33-1f20f6ad245c)

2024-04-24 15:18 UTC, jortilles commented on eda/eda_api/lib/module/dashboard/dashboard.controller.ts
> +        val.toString().indexOf('Z') >= 0 || val.toString().indexOf('Z') >= 0 || val.toString().replace(/['"]+/g, '').length == 0 ) {
No. Aplica. Lo hemos encontrado por el camino.  es sobre los valores nulos en los datos.  Busca carácteres especiales para determinar si un campo es numérico. ( -.´ç+¡)

2024-04-25 07:38 UTC, PaulaaSTIC requested changes
En un panel que incluye campos de dos módulos, uno de ellos siendo un desplegable, la consulta generada presenta un error en el left join. El error esta en como se genera la query que hace una comparación entre el valor "value" y el valor "code" ambos de la misma lista.


![error_query_builder](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/848747fa-bbde-4a97-bab9-cae4602bda03)
```
SELECT cast(sum(`sda_stic_events`.`N`) as decimal(32,0) ) as `(n) Eventos/Grupos`, `sda_l_stic_registrations_status_stic_registrations_status_list`.`value` as `Estado`  
FROM sda_stic_events 
inner JOIN `sda_stic_registrations` ON  `sda_stic_events`.`id` = `sda_stic_registrations`.`stic_registrations_stic_eventsstic_events_ida`  
LEFT JOIN `sda_l_stic_registrations_status_stic_registrations_status_list` ON  `sda_l_stic_registrations_status_stic_registrations_status_list`.`value` = `sda_l_stic_registrations_status_stic_registrations_status_list`.`code`  
group by `sda_l_stic_registrations_status_stic_registrations_status_list`.`value` 
order by `(n) Eventos/Grupos` Desc
```

2024-04-26 06:38 UTC, juanSTIC reviewed
**Se produce un error de Javascript que provoca que deje de funcionar la configuración de los filtros** y el boton de la rueda dentada, por lo que no se puede usar SinergiaDA.
Parece que el error se produce (al menos) _cuando se añade un nuevo panel_ en un informe que ya tiene algún filtro a nivel de informe.
![no_funcionan_opciones_configuracion](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/6597d616-5818-4516-bce3-9f9f78b6e51a)

2024-04-26 06:41 UTC, juanSTIC requested changes
Al intentar guardar un filtro de informe, si no se ha configurado alguna de las rutas, se muestra un error **Alert Invalid**, pero no se indica cuál es el error. Debe mostrarse un menaje más explícito y enviar el foco al input que ha provocado el error.

![filtro1](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/45a5f729-b786-452c-b4c4-9f91b5a0b1b5)

2024-04-26 06:57 UTC, juanSTIC requested changes
Al agregar un filtro a nivel de informe, si el módulo principal del panel es el mismo que el módulo por el que se está filtrando, o si solo hay un paso entre ellos  este debería seleccionarse automáticamente en el desplegable de la ruta, sin esperar a ninguna acción por parte del usuario. 
Si después el usuario decide escoger otra ruta, debe poder hacerlo.
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/0ed3af9f-0328-4f35-a2bf-75a3e3b12dbf)

2024-04-26 07:10 UTC, juanSTIC requested changes
En la pantalla de  filtros de informe, el área **Paneles para los que aplica el filtro** debería estar en estado **disabled** o similar mientras no este correctamente rellenos los dos primeros campos del área **Filtrar por**, para evitar errores y la mala experiencia del usuario.
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/ef8bc68f-add3-4f33-b5e2-4598990565bc)

2024-04-26 07:16 UTC, juanSTIC requested changes
En la pantalla de los filtros de informe, si un filtro está desactivado, el desplegable de la ruta debería estar oculto o desactivado (preferiblemente oculto)
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/7b4e52c2-12e0-402f-b551-837932c872c5)

2024-04-26 08:32 UTC, PaulaaSTIC requested changes

2024-04-26 08:32 UTC, PaulaaSTIC commented on eda/eda_app/src/app/module/components/eda-panels/eda-blank-panel/panel-utils/panel-interaction-utils.ts
> +              throw '[Error]: Can not remove this column cause there is a GlobalFilter linked.'
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/b56cf4c9-b1e7-49d0-b801-2c8303ccf5b5)
Incluir la cadena de este error en los ficheros de idiomas para poder hacer las traducciones.

2024-04-26 09:01 UTC, juanSTIC requested changes
**En el árbol de selección de campos se marca los módulos incluidos usando una ruta incorrecta.** 
Como se puede ver en la imagen, el módulo campaña aparece marcado dos (o más ) veces, pero solamente se ha incluido en el informe el nodo **Campañas** se ha incluido a partir de su relación con el módulo _Organizaciones_, sin embargo, también aparece marcado el nodo a partir de su relación con _Personas_. Aunque el SQL es correcto, la indicación sobre la ruta escogida debería ser inequívoca.

![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/49428ee6-362b-49f2-bb57-f9dee79b1b5e)

2024-04-26 09:51 UTC, PaulaaSTIC requested changes
En el **Resumen de columnas** agregar el camino seleccionado para poder identificar de dónde provienen los campos.

![Screenshot from 2024-04-26 11-41-35](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/0b3d23f0-0410-4e87-9a4a-d18c09329d7e)

2024-04-26 10:00 UTC, PaulaaSTIC requested changes
**Error en los filtros de panel.**

En algunas ocasiones, al agregar el tipo de filtro, se añade incorrectamente y no permite seleccionar el toggle para desplegar opciones. Y en las ocasiones en las que se puede seleccionar 'Opciones', se produce`error quering database`.

![error filtros nivel panel](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/566ff1ca-c775-4f2e-a65e-f541dcd493af)

2024-05-06 05:43 UTC, jortilles commented
Hola.
Todos los issues ya están resueltos. Ya se puede volver a validar.
Saludos.

2024-05-08 16:03 UTC, PaulaaSTIC requested changes
**Error en filtro de panel cuando hay filtros en el informe**
Si en un informe con filtros en uno de los paneles intentamos añadir un filtro de un campo de un módulo relacionado, se produce un error en la consulta a la base de datos.
![Error al filtrar si hay filtros](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/1f6c47d6-d4e7-400c-8655-336010bb2135)

2024-05-09 07:27 UTC, PaulaaSTIC requested changes
**Si hay filtros no se pueden ejecutar nuevos paneles.**
Cuando hay un filtro presente e intentamos añadir un nuevo panel, se produce un error en la consulta a la base de datos. Debería ser posible incluir el nuevo panel en el informe sin necesidad de eliminar los filtros. Esto puede estar ocurriendo porque al no haber marcado la ruta del filtro para el nuevo panel, no se puede ejecutar la consulta, pero tampoco se puede definir la ruta del panel sin antes crearlo. Los paneles deberían aparecer deshabilitados para los filtros hasta que se definan.
Si en lugar de crear un panel desde cero duplicamos uno presente en el informe, lo marcamos para que no se filtre y lo editamos, la consulta se ejecutará correctamente.

![error si hay filtro](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/cdc6484f-2a14-4339-888b-0800f97383a8)

2024-05-09 09:43 UTC, PaulaaSTIC requested changes
Si un filtro a nivel de panel se modifica para filtrar un campo distinto al elegido inicialmente, no siempre se actualizan los valores del nuevo campo. Es necesario guardar el informe, volver a cargarlo y entonces sí aparecen los valores del nuevo filtro.
![cambiar campo del filtro](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/98e923f9-fee4-4bc5-b2d9-be19cc19f30a)

2024-05-10 08:34 UTC, jortilles commented
El problema del último issue es que no se refresca el selector.

2024-05-13 15:17 UTC, jortilles commented
Hemos hecho un nuevo commit resolviendo todos los issues:
Tablas repetidas:
<img width="640" alt="image" src="https://github.com/SinergiaTIC/SinergiaDA/assets/1340212/e7cfadc7-11e3-4416-9cd9-f37975bb22d5">

Filtros:
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/1340212/6265efe4-a525-4e23-a11d-76e24e2e671b)

Añadir nuevos paneles.

Cambio en la configuración del filtro.

2024-05-14 17:06 UTC, PaulaaSTIC commented
**Filtros de informe fijos**
Cuando se filtra un informe que contiene más de un filtro, incluso si se eliminan todos los filtros posteriormente, parte de los filtros iniciales permanecen guardados en las consultas de los paneles.

![Filtros mal al filtrar](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/22636867-165d-4fe3-87c5-fed7b4af6e5e)

2024-05-14 17:07 UTC, PaulaaSTIC requested changes
**Filtros de informe fijos**
Cuando se filtra un informe que contiene más de un filtro, incluso si se eliminan todos los filtros posteriormente, parte de los filtros iniciales permanecen guardados en las consultas de los paneles.

![Filtros mal al filtrar](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/22636867-165d-4fe3-87c5-fed7b4af6e5e)

2024-05-14 17:14 UTC, PaulaaSTIC commented
**Petición de mejora:**
Incluir un resumen del camino seguido en los filtros de panel y en los filtros de informe.
![Screenshot from 2024-05-14 19-10-34](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/0786113e-e0c0-4b5b-8c95-d5329138f539)
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/25998f15-7499-40ba-b169-6b60e9c1ce30)

2024-05-15 09:10 UTC, juanSTIC commented
**Compatibilidad con informes anteriores**
Se ha visto que en los informes anteriores, diseñados con el modo EDA no cargan correctamente los paneles que contiene relaciones entre diferentes módulo. 
Esta compatibilidad debe garantizarse asegurando de manera especial lo siguiente:
**1. Al cargar los informes deben mostrarse todos los paneles tal como lo hacen actualmente**
**2. Los informes deben poder editarse ya en el nuevo modo árbol.**

2024-05-15 09:11 UTC, juanSTIC requested changes
Ver comentarios

2024-05-15 09:36 UTC, juanSTIC requested changes
**Se ha modificado el panel de columnas, afectando a la posibilidad de reordenar las mismas**
En la nueva versión, al añadir columnas, si estas sobrepasan el tamaño del contenedor, pasan a una segunda fila, impidiendose su recolocación:
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/7ef4f1d1-6443-420e-b969-7aff52a15fa1)

Hay que recuperar el modo que ya existía en SinergiaDA, dónde todas las columnas quedan en una única fila:
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/8e78067b-dcfa-4c81-ade5-22a585c08da7)

2024-05-20 10:56 UTC, juanSTIC commented
> **Compatibilidad con informes anteriores** Se ha visto que en los informes anteriores, diseñados con el modo EDA no cargan correctamente los paneles que contiene relaciones entre diferentes módulo. Esta compatibilidad debe garantizarse asegurando de manera especial lo siguiente: **1. Al cargar los informes deben mostrarse todos los paneles tal como lo hacen actualmente** **2. Los informes deben poder editarse ya en el nuevo modo árbol.**

Se ha estimado que esta parte de lo solicitado queda pendiente de valoración y si es necesario se abordará fuera de este PR

2024-05-20 21:19 UTC, jortilles commented
Yo creo que ya está todo. Todo vuestro.

2024-05-21 07:12 UTC, juanSTIC commented
> **Se ha modificado el panel de columnas, afectando a la posibilidad de reordenar las mismas** En la nueva versión, al añadir columnas, si estas sobrepasan el tamaño del contenedor, pasan a una segunda fila, impidiendose su recolocación: ![image](https://private-user-images.githubusercontent.com/46187267/330747652-7ef4f1d1-6443-420e-b969-7aff52a15fa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzU2ODIsIm5iZiI6MTcxNjI3NTM4MiwicGF0aCI6Ii80NjE4NzI2Ny8zMzA3NDc2NTItN2VmNGYxZDEtNjQ0My00MjBlLWI5NjktN2FmZjUyYTE1ZmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA3MDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZWRhZjMzOGY4OWFlNjIwOTA0Zjk3OTNjMmQ3ZDA4N2U4MzlhZjcyMjUxN2Y1OGVmZGZmNWE0ODYwYzU3ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZYJ8PaoEpVu_VD_DzfmNfzOygebKMDVXAI1leo_HHv4)
> 
> Hay que recuperar el modo que ya existía en SinergiaDA, dónde todas las columnas quedan en una única fila: ![image](https://private-user-images.githubusercontent.com/46187267/330748032-8e78067b-dcfa-4c81-ade5-22a585c08da7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzU2ODIsIm5iZiI6MTcxNjI3NTM4MiwicGF0aCI6Ii80NjE4NzI2Ny8zMzA3NDgwMzItOGU3ODA2N2ItZGNmYS00YzgxLWFkZTUtMjJhNTg1YzA4ZGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA3MDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMjU4ZTQ2YTNmMDgyOTMyOWRlYjc0NDA1Y2U4YzJkODAxNzE1YTIxM2Y2M2M3YmQ4MjU0ZDlhZTVhZTRmZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l-G-adPCgDTdllhYkH6u7wKBat7WGM8IFSSPD1kN7gU)

Esta funcionalidad se había revertido parcialmente, quedando el texto de las columnas mal alineado y solapándose. En este [commit](https://github.com/SinergiaTIC/SinergiaDA/pull/140/commits/7838dd1e7a63127b157836b8a50e423a708f00d9) se ha revertido completamente a la funcionalidad anterior. Aparentemente no afecta en nada a la funcinalidad, pero será mejor una revisión por tu parte @jortilles

2024-05-21 09:35 UTC, juanSTIC requested changes
No funciona correctamente al pasar del Modo Árbol al Modo SQL, ya que el SQL aparece vacío.
![sqlmodeerror](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/c12f4311-60e4-41da-88f9-4733f90f4b2f)

2024-05-21 16:12 UTC, PaulaaSTIC commented
**Petición de mejora:**
Eliminar de los nuevos paneles la opción de EDA query para mantener la coherencia con los paneles generados en modo tree query. De esta forma, la opción EDA query solo aparecerá disponible en los antiguos paneles EDA.

![Screenshot from 2024-05-21 18-07-41](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/6a85784b-9fea-44a1-b351-96f9b19297fa)

2024-05-22 21:38 UTC, jortilles commented
> ###
> <img alt="@juanSTIC" width="24" height="24" src="https://avatars.githubusercontent.com/u/46187267?s=48&amp;v=4"> ** [juanSTIC](/juanSTIC) ** left a
 Nunca ha funcionado así. Cuando pasas de un modo al otro se resetea la consulta. Sólo puedes "abrir la consulta en modo SQL " 

https://github.com/SinergiaTIC/SinergiaDA/assets/1340212/0bb768c6-79ad-4736-b17e-53c975a1f250

2024-05-23 08:05 UTC, juanSTIC commented
> > <img alt="@juanSTIC" width="24" height="24" src="https://avatars.githubusercontent.com/u/46187267?s=48&amp;v=4"> ** [juanSTIC](/juanSTIC) ** left a
> > Nunca ha funcionado así. Cuando pasas de un modo al otro se resetea la consulta. Sólo puedes "abrir la consulta en modo SQL "
> 
>  consultaSQL.mp4

De acuerdo, en cualquier modo, se puede abrir desde el tooltip que muestra la consulta Sql.

2024-05-27 10:52 UTC, PaulaaSTIC requested changes
**Error en panel nuevo EDA-Tree query**
![Error_EDA_Tree_Query](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/c14422f9-b6bf-4bcc-9339-1d99a416096f)

2024-05-27 14:20 UTC, juanSTIC submitted a review, later dismissed

2024-05-28 17:49 UTC, jalbaiges approved these changes
Cadenas revisadas

2024-05-29 09:18 UTC, PaulaaSTIC approved these changes
(A)probado

2024-05-29 09:18 UTC, juanSTIC approved these changes
Aprobado

2024-05-29 09:19 UTC, merged