Bug - API - Fallo en updateModel al actualizar pertenencia a grupos de seguridad #135
SinergiaTIC/SinergiaDA pull request #143
Opened 2024-04-26 13:40 UTC by jortilles

## Descripción del Cambio
Refactorización para anadir los grupos.

## Issue(s) resuelto(s)
- solves  https://github.com/SinergiaTIC/SinergiaDA/issues/135
- solves https://github.com/SinergiaTIC/SinergiaDA/issues/128

## Pruebas a realizar para validar el cambio
Mover los grupos de seguridad de un usuario y comprobar el funcionamiento. Tal y como se describe en el issue.

2024-04-29 10:38 UTC, juanSTIC requested changes
Da error directamente al ejecutar updateModel, se muetsra el siguiente error:

![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/7f998a24-35d5-4842-81f9-3117f74cba3d)

2024-05-20 11:36 UTC, PaulaaSTIC requested changes
Da error la conexión, ocurre antes de llamar al updateModel
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/b954d88a-7a0c-4161-bec8-862beb60d076)

2024-05-20 12:39 UTC, asafJortilles commented
@PaulaaSTIC Al hacer el cambio en la forma en la que tomamos los datos de grupos desde el CRM, @juanSTIC se dio cuenta que el módulo de crear un grupo SDA_BASIC era innecesario. Es posible que Juan lo haya eliminado en vuestro local y por eso peta en esas 2 lineas.  Puedes flaguear ambas lineas donde se hace la llamada a este modulo para probar?

2024-05-21 10:57 UTC, PaulaaSTIC requested changes
Comprobando el issue #135 he eliminado un usuario, he ejecutado el update model pero no se actualiza la pertenencia de grupos. Por ejemplo, el usuario u2 de mi instancia anteriormente pertenecía a G2. Le he quitado de G2 y le he añadido a G4, pero ahora ambos grupos aparecen asociados al usuario, aunque en la tabla sda_def_users_groups solo figura G4.


![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/38135fe4-22aa-4a3d-b7da-34002e2062ff)
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/787cd02a-6f92-448d-b050-d033e934efcb)

2024-05-21 11:28 UTC, juanSTIC requested changes
Se ha comprobado que no se trasladan los permiso definidos en la tabla sda_def_permissions.

Como ejemplo, en la tabla sda_def_permissions está definido lo siguiente:
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/2cb3988d-6870-4845-accd-3a106740b56c)


pero, tras ejecutar updateModel los permisos sobre la tabla _sda_stic_sepe_actions_ no se han modificado.

![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/a9b2a8e8-97aa-44d7-9421-7e9f37a7fb7e)

2024-05-21 11:51 UTC, PaulaaSTIC requested changes
**Error entre usuarios.**
En el CRM hay un usuario **u1** cuyo correo es u1@test.com, y en SDA hay un usuario **u1** con el correo u1@u1.com. Los permisos que vienen del CRM se están actualizando en el usuario u1@u1.com en lugar de en el usuario del CRM.

Debería comprobarse tanto el nombre como el correo electrónico a la hora de establecer permisos en un usuario. Si elimino el usuario u1@test.com deel CRM en SDA me lo genera de nuevo con los permisos correctos.




![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/e6ac09d1-9c89-4421-9774-857115cff627)

![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/5e80519e-4c37-4843-b8ef-b1686cd2d3fc)
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/653c6a6e-508f-44c5-8e3b-377750bba736)

2024-05-22 15:43 UTC, asafJortilles commented
> **Error entre usuarios.** En el CRM hay un usuario **u1** cuyo correo es [u1@test.com](mailto:u1@test.com), y en SDA hay un usuario **u1** con el correo [u1@u1.com](mailto:u1@u1.com). Los permisos que vienen del CRM se están actualizando en el usuario [u1@u1.com](mailto:u1@u1.com) en lugar de en el usuario del CRM.
> 
> Debería comprobarse tanto el nombre como el correo electrónico a la hora de establecer permisos en un usuario. Si elimino el usuario [u1@test.com](mailto:u1@test.com) deel CRM en SDA me lo genera de nuevo con los permisos correctos.
> 
> ![image](https://private-user-images.githubusercontent.com/125350097/332413897-e6ac09d1-9c89-4421-9774-857115cff627.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODc2NTQsIm5iZiI6MTcxNjM4NzM1NCwicGF0aCI6Ii8xMjUzNTAwOTcvMzMyNDEzODk3LWU2YWMwOWQxLTljODktNDQyMS05Nzc0LTg1NzExNWNmZjYyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxNDE1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGQwYTkzZDE5MmIyNDNjODhlMGFkNGRmYTMyMzcxNjI3NjIwOWI1NjJmY2MxNGJmYzEzMTUwN2IwYThiYjA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fvOli2zY_PlubVp99PHrXC3CE-PPLu58NLqWrCrmx-U)
> 
> ![image](https://private-user-images.githubusercontent.com/125350097/332412714-5e80519e-4c37-4843-b8ef-b1686cd2d3fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODc2NTQsIm5iZiI6MTcxNjM4NzM1NCwicGF0aCI6Ii8xMjUzNTAwOTcvMzMyNDEyNzE0LTVlODA1MTllLTRjMzctNDg0My1iOGVmLWIxNjg2Y2QyZDNmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxNDE1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODk1MDczMGJjNWU0ZGFhZjIwM2I0ODNhOWU3OTAwN2JkMDgwMzY4ZTQzZTdhZDFhODE1MGZjZWVlYTIyZWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5RhgZvOzIG_rM_hGYwqqPadvAdbZP-mrI5Ig-v6K5pk) ![image](https://private-user-images.githubusercontent.com/125350097/332413737-653c6a6e-508f-44c5-8e3b-377750bba736.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODc2NTQsIm5iZiI6MTcxNjM4NzM1NCwicGF0aCI6Ii8xMjUzNTAwOTcvMzMyNDEzNzM3LTY1M2M2YTZlLTUwOGYtNDRjNS04ZTNiLTM3Nzc1MGJiYTczNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxNDE1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTk5YjBlNjZmMGRiOGI2NWM5ZjllZGIwYjNmMjgyMTA4ZjI2NjZjNDAyMjBjYzJiM2E3NTU5YjkzMWJkNTk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rJJ58ttRuoEPj9TMUGYyya2EGCnaH6snaH2Rp8pm_zY)

@PaulaaSTIC no he sido capaz de reproducir el error, he intentado crear el usuario con distinto mail pero mismo user y he conseguido mantener inalterado el usuario en SDA y traer el usuario del CRM con sus permisos pertinentes.

2024-05-27 10:44 UTC, PaulaaSTIC commented
Error al ejecutar el UpdateModel
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/b4614be5-7652-4d29-b48f-98e39a0dbd4d)

2024-06-12 08:49 UTC, juanSTIC requested changes
Sigue dando error al ejecutar updateModel.

Aunque la versión de mongoDB es diferente, no parece que esta sea la causa del problema, ya que con otros PR no existe el problema

2024-06-13 13:46 UTC, jortilles commented
@PaulaaSTIC  @juanSTIC  puedes volver a validar, por favor.

2024-06-13 14:19 UTC, PaulaaSTIC requested changes
El updateModel funciona correctamente, pero la rama no está actualizada con reporting.

2024-06-14 04:26 UTC, jortilles commented
Ya se ha sincronizado

2024-06-24 06:49 UTC, juanSTIC commented
Sincronizada con la última versión de reporting

2024-06-26 11:20 UTC, juanSTIC approved these changes
Visto y probado

2024-06-26 11:20 UTC, merged