Hotfix - APP.  Sda#53 Corrección paneles SQL no recargan datos
SinergiaTIC/SinergiaDA pull request #151
Opened 2024-06-03 05:40 UTC by jortilles

Cambio en la app al comprobar el tipo de panel  para los paneles SQL.  

## Issue(s) resuelto(s)

- solves https://github.com/SinergiaTIC/SinergiaDA/issues/148

## Pruebas a realizar para validar el cambio
Hacer un infomre con un panel SQL y un gráfico de barras. Al recargar el informe sigue funcionando correctamente.

## Información Adicional
El error se debia al hacer la comprobación para mantener la compatibilidad con versiones antiguas

2024-06-03 10:10 UTC, juanSTIC requested changes
Hay conflictos sin resolver

2024-06-03 10:10 UTC, jortilles commented
Conflictos resueltos.

2024-06-04 06:46 UTC, juanSTIC requested changes
Cuando hay una autorelación el módulo aparece repetido _n_ veces, cuando solo debería salir una sola
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/aded6790-018a-43a1-b5e1-0766b9f11ba1)

2024-06-04 14:35 UTC, jortilles commented
Ya he quitado el duplicado de las relaciones para las relaciones. 

El pantallazo anterior ahora es correcto:

![image](https://github.com/SinergiaTIC/SinergiaDA/assets/1340212/8a1ca537-b5a6-43e6-8338-cfbd6125ed83)


que responde a:

![image](https://github.com/SinergiaTIC/SinergiaDA/assets/1340212/b2cd1c9b-4c33-4fb2-8624-b77dff3d92d8)

2024-06-04 17:05 UTC, juanSTIC requested changes
**Error en el uso de las autorelaciones**
Aunque las autorelaciones aparecen correctamente representadas en el árbol, cuando hay más de una autorelación (lo cual es una situación frecuente) **solamente es posible usar una de ellas**, ya que, aunque hagamos click en la otra,  solamente se utiliza una. Se puede comprobar como en la imagen, aunque se haga click en _subevento1_, siempre se muestran los datos de _subevento2_

![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/d298dad0-cd62-4e1d-abe2-59640711dced)

2024-06-10 11:52 UTC, PaulaaSTIC requested changes
Si partimos desde Evento/Grupos permite hacer referencia a las autorelaciones, se ejecuta la query pero si guardamos y recargamos la página desaparecen las autorelaciones de la query.
![autorelaciones_subevento](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/9fb95d13-e4cc-4650-9218-8fa95569d17e)

2024-06-10 11:55 UTC, juanSTIC requested changes
Hemos visto que da error siempre que comencemos el árbol en un módulo diferente del que contiene la autorelación.

En este caso se construye incorrectamente la SQL, usando un nombre de columna inexistente:
```SQL
SELECT `sda_stic_registrations`.`name` as `Nombre`, `sda_stic_events`.`name` as `Nombre_1`, `sda_stic_registrations.stic_registrations_stic_eventsstic_events_ida`.`name` as `Nombre_2`
FROM sda_stic_registrations
inner JOIN `sda_stic_events` ON  `sda_stic_registrations`.`stic_registrations_stic_eventsstic_events_ida` = `sda_stic_events`.`id`
inner JOIN `sda_stic_events` `sda_stic_eventsstic_events_id_c` ON  `sda_stic_events`.`stic_events_id_c`  =  `sda_stic_eventsstic_events_id_c`.`id`
group by `sda_stic_registrations`.`name`, `sda_stic_events`.`name`, `sda_stic_registrations.stic_registrations_stic_eventsstic_events_ida`.`name`

#1054 - Unknown column 'sda_stic_registrations.stic_registrations_stic_eventsstic_events_ida.name' in 'field list'
```

2024-06-12 05:43 UTC, jortilles commented
Con los últimos cambios tenemos un entorno "estable". Para poder explorar las auto-relaciones necesitaremos un poco más de esfuerzo

2024-06-12 06:54 UTC, juanSTIC requested changes
Las autorelaciones parecen funcionar correctamente según lo esperado, sin embargo al guardar el informe y recargar solamente se guardan los campos del módulo principal. Esto es lo mismo que ya ocurrió en las primera validaciones del PR del árbol y que se reporto aquí https://github.com/SinergiaTIC/SinergiaDA/pull/140#issuecomment-2058518004

Es similar a lo ya reportado por @PaulaaSTIC aqui https://github.com/SinergiaTIC/SinergiaDA/pull/151#pullrequestreview-2107576878

2024-06-12 16:37 UTC, juanSTIC approved these changes
Aprobado

2024-06-12 16:38 UTC, merged