Improvement APP+API Permitir filtrar "vacío" a nivel informe SDA#126
SinergiaTIC/SinergiaDA pull request #153
Opened 2024-06-04 13:28 UTC by jortilles

## Descripción del Cambio
Se cambia el comportamiento para que se permita filtrar "vacio" a nivell de informe.
SE ESTABLECE UN VAOR POR DEFECTO PARA LOS NULOS. que hemos inicializado a 'null'
CABE DESTACAR QUE UN VALOR NULO Y UNA CADENA VACIA '' SON VALORES DISTINTOS. Nosotros tratamos los nulos.  

## Issue(s) resuelto(s)
- solves https://github.com/SinergiaTIC/Sinergia-Data-Analytics/issues/126
- solves https://github.com/SinergiaTIC/SinergiaDA/issues/58
- solves https://github.com/SinergiaTIC/SinergiaDA/issues/56
- solves https://github.com/SinergiaTIC/SinergiaDA/issues/147
## Pruebas a realizar para validar el cambio
Realizar un informe donde haya paneles con valores nulos y comprobar el funcionamiento.
Hacer un informe con varios filtros sobre una misma columna
Hacer un iforme con varios filtros sobre una columna. Uno de los cuales debe ser el valor nulo.

## Información Adicional
Este PR entra en conflicto con https://github.com/SinergiaTIC/SinergiaDA/pull/119  Debe integrarse despues que ese

2024-06-04 16:07 UTC, PaulaaSTIC approved these changes
Al aplicar dos filtros sobre la misma columna, la consulta se genera incorrectamente, repitiendo la misma condición dos veces. Esto provoca un `Error quering database
`
![error dentro de fuera de](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/5a2a65cf-f858-4c20-aaa7-fa9cd1c8fa1b)

```
SELECT `sda_stic_payment_commitments`.`name` as `Nombre`, DATE_FORMAT(`sda_stic_payment_commitments`.`date_entered`, '%Y-%m-%d') as `Fecha de Creación`  
FROM sda_stic_payment_commitments 
where  ( `sda_stic_payment_commitments`.`date_entered`  > '2014-07-10'  
  or `sda_stic_payment_commitments`.`date_entered`  > '2014-07-10' `sda_stic_payment_commitments`.`date_entered`  < '2016-06-22'  
  or `sda_stic_payment_commitments`.`date_entered`  < '2016-06-22'  )  
group by `sda_stic_payment_commitments`.`name`, `sda_stic_payment_commitments`.`date_entered`
```

2024-06-04 16:22 UTC, PaulaaSTIC requested changes
Filtrar un valor numérico produce `Error quering database` 

![error SQL](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/0d316221-5e42-4c04-a2a8-40adde170fd6)

2024-06-05 04:41 UTC, jortilles commented
Visto el error y corregido

2024-06-05 07:48 UTC, PaulaaSTIC requested changes
Al aplicar dos filtros sobre la misma columna, la consulta se genera incorrectamente, repitiendo la misma condición dos veces. Esto provoca un `Error quering database
`
![error dentro de fuera de](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/5a2a65cf-f858-4c20-aaa7-fa9cd1c8fa1b)

```
SELECT `sda_stic_payment_commitments`.`name` as `Nombre`, DATE_FORMAT(`sda_stic_payment_commitments`.`date_entered`, '%Y-%m-%d') as `Fecha de Creación`  
FROM sda_stic_payment_commitments 
where  ( `sda_stic_payment_commitments`.`date_entered`  > '2014-07-10'  
  or `sda_stic_payment_commitments`.`date_entered`  > '2014-07-10' `sda_stic_payment_commitments`.`date_entered`  < '2016-06-22'  
  or `sda_stic_payment_commitments`.`date_entered`  < '2016-06-22'  )  
group by `sda_stic_payment_commitments`.`name`, `sda_stic_payment_commitments`.`date_entered`
```

2024-06-05 10:53 UTC, jortilles commented
Ya esta resuelto el tema de la duplicación de los filtros.

2024-06-05 13:51 UTC, juanSTIC approved these changes
Aprobado

2024-06-05 13:51 UTC, PaulaaSTIC approved these changes
(A)probado

2024-06-05 13:52 UTC, merged