Improvement - APP Sda#160 Conservar representación y estilos al editar panel
SinergiaTIC/SinergiaDA pull request #156
Opened 2024-06-07 04:38 UTC by jortilles

## Descripción del Cambio
Cuando se cambia un panel. Por defecto se resetea la configuración del gráfico al no poder garantizar que la consulta se pueda renderizar con el mismo gráfico.
Ahora se vuelve a comprobar la viabilidad del gráfico. Y si se puede renderizar se mantiene la configuración.

## Issue(s) resuelto(s)

- solves https://github.com/SinergiaTIC/Sinergia-Data-Analytics/issues/160

## Pruebas a realizar para validar el cambio
Realizar un panel. Configurar las opciones del gráfico y cambiar la consulta sin que cambien el número de columnas de texto y numéricas.

2024-06-10 08:45 UTC, juanSTIC requested changes
El PR está basado en una versión antigua de la rama _reporting_. por lo que el modo por defecto aún es el modo EDA (y no el modo árbol) y aparece un mensaje de Server Error. 
Debe actualizarse con la rama reporting y **realizar pruebas a fondo antes de pasarse nuevamente a validación**.
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/c123b151-16d7-493f-a132-056012180a54)

2024-07-24 08:26 UTC, juanSTIC requested changes
Se produce un error al ejecutar cualquier consulta.

2024-08-06 10:00 UTC, jortilles commented
Ya se puede volver a probar.

2024-08-19 11:05 UTC, juanSTIC approved these changes
Visto y probado

2024-08-19 11:29 UTC, PaulaaSTIC approved these changes
(A)Probado

2024-09-03 08:55 UTC, merged