Enhancement/home2
SinergiaTIC/SinergiaDA pull request #159
Opened 2024-06-13 14:22 UTC by juanSTIC

Alternative home

2024-08-29 10:10 UTC, PaulaaSTIC requested changes
Dejo por aquí algunas cosas que he visto:

- No se puede editar el nombre del informe en la vista de lista.
- El filtrado por tipo de informe aparece en blanco hasta que seleccionas alguno de los tipos. Al hacerlo, se vuelve negro, pero no filtra bien; debes hacer clic de nuevo para que la opción seleccionada se muestre en blanco, y entonces sí filtra correctamente.
![filtro_por_grupo](https://github.com/user-attachments/assets/1bd4ea74-d361-469d-80e9-413bdc2cf86e)

- Si duplicas un informe de grupo, queda un rastro de la etiqueta del grupo, pero está vacía. 
![image](https://github.com/user-attachments/assets/d9a5edb8-12c2-428c-8381-2cdc3739198b)

- El filtro de Grupos no carga las opciones presentes en los informes.

2024-08-29 10:22 UTC, AlbertoSTIC requested changes
La nueva pantalla tiene muy buena pinta. Dejo algunos comentarios de cosas que he visto:
- No he conseguido que me aparezcan grupos para filtrar el apartado de grupos. He añadido a mi usuario en un par de grupos y he asignado grupos a los informes. No estoy seguro si es porque mi usuario es SinergiaCRM.
![Selection_404](https://github.com/user-attachments/assets/3b10ee75-7bf5-4ccc-83ca-94ac07e1f26e)
- Me parece que la distribución de componentes en el menú están demasiado espaciados. Creo que juntaría algunos de los botones/filtros según la tipología. 
- Los botones dentro del filtro de "Type" de "common" y "público" me parecen confusos. El de "common" me recuerda a un informe púbico y el de "public" no lo tengo claro.
- En el mismo contexto del filtro de "Type", creo que añadiría un botón para seleccionar "todos". Me ha costado saber que para hacer esto, hay que clickar en el ultimo tipo seleccionado.

Tengo la duda si hay que evaluar la vista responsive en este PR. Si hay que hacerlo, diría que hay que darle alguna vuelta, por una parte el número de columnas no se ajusta automáticamente, ni el tamaño de los filtros. Luego, en la vista de Informe, faltaría una manera de poder volver a la vista de lista.

2024-09-03 09:07 UTC, juanSTIC commented
Al clonar un informe de grupos, se pierden los mismos (en algunas circunstancias)

2024-09-05 16:26 UTC, juanSTIC commented
> Al clonar un informe de grupos, se pierden los mismos (en algunas circunstancias).
> 
> Al editar nombre o tipo se pierde la información de los grupos

Resuelto

> La nueva pantalla tiene muy buena pinta. Dejo algunos comentarios de cosas que he visto:
> 
> * No he conseguido que me aparezcan grupos para filtrar el apartado de grupos. He añadido a mi usuario en un par de grupos y he asignado grupos a los informes. No estoy seguro si es porque mi usuario es SinergiaCRM.
>   ![Selection_404](https://private-user-images.githubusercontent.com/46563429/362636035-3b10ee75-7bf5-4ccc-83ca-94ac07e1f26e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTM4MDIsIm5iZiI6MTcyNTU1MzUwMiwicGF0aCI6Ii80NjU2MzQyOS8zNjI2MzYwMzUtM2IxMGVlNzUtN2JmNS00Y2NjLTgzY2EtOTRhYzA3ZTFmMjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDE2MjUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiY2Q1MmI3MTI0ZTRjNWNmZGQxNTZiMWExZjc2ODk5NWQxYTYwYmJiNDE1NGQ0N2Y5YTUyYjAxNzkxMmU4MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VzjcrB-IGr0Mj6Sg1dkMjHnP3z3G009k6EAFAq1GxZU)
> * Me parece que la distribución de componentes en el menú están demasiado espaciados. Creo que juntaría algunos de los botones/filtros según la tipología.
> * Los botones dentro del filtro de "Type" de "common" y "público" me parecen confusos. El de "common" me recuerda a un informe púbico y el de "public" no lo tengo claro.
> * En el mismo contexto del filtro de "Type", creo que añadiría un botón para seleccionar "todos". Me ha costado saber que para hacer esto, hay que clickar en el ultimo tipo seleccionado.
> 
> Tengo la duda si hay que evaluar la vista responsive en este PR. Si hay que hacerlo, diría que hay que darle alguna vuelta, por una parte el número de columnas no se ajusta automáticamente, ni el tamaño de los filtros. Luego, en la vista de Informe, faltaría una manera de poder volver a la vista de lista.

Se han resulto algunos de los errores planteados y se han seguido alguna de las sugerencias.

2024-09-05 16:26 UTC, juanSTIC commented
> Dejo por aquí algunas cosas que he visto:
> 
> * No se puede editar el nombre del informe en la vista de lista.
> * El filtrado por tipo de informe aparece en blanco hasta que seleccionas alguno de los tipos. Al hacerlo, se vuelve negro, pero no filtra bien; debes hacer clic de nuevo para que la opción seleccionada se muestre en blanco, y entonces sí filtra correctamente.
>   ![filtro_por_grupo](https://private-user-images.githubusercontent.com/125350097/362633137-1bd4ea74-d361-469d-80e9-413bdc2cf86e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTM4MDIsIm5iZiI6MTcyNTU1MzUwMiwicGF0aCI6Ii8xMjUzNTAwOTcvMzYyNjMzMTM3LTFiZDRlYTc0LWQzNjEtNDY5ZC04MGU5LTQxM2JkYzJjZjg2ZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxNjI1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWNkMzAwYmRjNDlkODEyNzM2YTMyZTBhYzQyYzcwNjExMDBmNjBmMGMyMWNjZjAyMjI4ZjA1Yzk2YTU1MTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1r4kMugPehD0sD3qcHZNa8J8tE7v1BCZEl1dOSW33Ic)
>         
>           [
>             
>           
>               ![filtro_por_grupo](https://private-user-images.githubusercontent.com/125350097/362633137-1bd4ea74-d361-469d-80e9-413bdc2cf86e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTM4MDIsIm5iZiI6MTcyNTU1MzUwMiwicGF0aCI6Ii8xMjUzNTAwOTcvMzYyNjMzMTM3LTFiZDRlYTc0LWQzNjEtNDY5ZC04MGU5LTQxM2JkYzJjZjg2ZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxNjI1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWNkMzAwYmRjNDlkODEyNzM2YTMyZTBhYzQyYzcwNjExMDBmNjBmMGMyMWNjZjAyMjI4ZjA1Yzk2YTU1MTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1r4kMugPehD0sD3qcHZNa8J8tE7v1BCZEl1dOSW33Ic)
>             ](https://private-user-images.githubusercontent.com/125350097/362633137-1bd4ea74-d361-469d-80e9-413bdc2cf86e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTM4MDIsIm5iZiI6MTcyNTU1MzUwMiwicGF0aCI6Ii8xMjUzNTAwOTcvMzYyNjMzMTM3LTFiZDRlYTc0LWQzNjEtNDY5ZC04MGU5LTQxM2JkYzJjZjg2ZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxNjI1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWNkMzAwYmRjNDlkODEyNzM2YTMyZTBhYzQyYzcwNjExMDBmNjBmMGMyMWNjZjAyMjI4ZjA1Yzk2YTU1MTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1r4kMugPehD0sD3qcHZNa8J8tE7v1BCZEl1dOSW33Ic)
>           
>           
>             
>               
>                 
>               
>               
>                 
>                 
>               
>             
>             [
>               
>                 
>               
>             ](https://private-user-images.githubusercontent.com/125350097/362633137-1bd4ea74-d361-469d-80e9-413bdc2cf86e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTM4MDIsIm5iZiI6MTcyNTU1MzUwMiwicGF0aCI6Ii8xMjUzNTAwOTcvMzYyNjMzMTM3LTFiZDRlYTc0LWQzNjEtNDY5ZC04MGU5LTQxM2JkYzJjZjg2ZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxNjI1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWNkMzAwYmRjNDlkODEyNzM2YTMyZTBhYzQyYzcwNjExMDBmNjBmMGMyMWNjZjAyMjI4ZjA1Yzk2YTU1MTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1r4kMugPehD0sD3qcHZNa8J8tE7v1BCZEl1dOSW33Ic)
> * Si duplicas un informe de grupo, queda un rastro de la etiqueta del grupo, pero está vacía.
>   ![image](https://private-user-images.githubusercontent.com/125350097/362632593-d9a5edb8-12c2-428c-8381-2cdc3739198b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTM4MDIsIm5iZiI6MTcyNTU1MzUwMiwicGF0aCI6Ii8xMjUzNTAwOTcvMzYyNjMyNTkzLWQ5YTVlZGI4LTEyYzItNDI4Yy04MzgxLTJjZGMzNzM5MTk4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxNjI1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzRlNzA1MTg3ZjdhODJmOWM1YjEzOTIwZTA4YjAzMjMzNDUwMzZlZDg4MWFkNTA5NzEyZjNiMjdjNjhiYmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uAyDFhHRGT4ej-D_DE7pu8fYyStxB6BKY3r1JMXawbQ)
> * El filtro de Grupos no carga las opciones presentes en los informes.

Resueltos los errores indicados

2024-09-06 06:54 UTC, juanSTIC commented
- Corregir la ordenación en la vista de lista para el campo Edición Privada y el campo de tipo. Actualmente, los agrupa pero no los ordena alfabéticamente.

- Implementar la funcionalidad de abrir el informe al hacer clic en el nombre del informe en la vista de lista.

- Revisar y corregir las traducciones al catalán, especialmente para términos como "Fuente de Datos", "Grupos", "Etiquetas" en la página inicial.

- Ajustar los colores utilizados en la interfaz para que coincidan con los colores corporativos de SinergiaTIC. Esto incluye los colores de iconos, etiquetas, botón de nuevo informe, filtros, y colores por tipo de informe. Se sugiere usar los colores corporativos de SinergiaTIC o variaciones de estos, que se pueden encontrar en: https://wikiorg.sinergiacrm.org/index.php?title=Kit_de_supervivencia#Colores_corporativos_de_SinergiaTIC

2024-09-06 07:42 UTC, juanSTIC commented
- Si no eres administrador, al entrar no se ven los informes y es necesario poner y quitar un filtro para que se muestren

2024-09-06 07:44 UTC, juanSTIC commented
- Si no eres administrador, aparecen las etiquetas de grupo vacías

2024-09-06 07:46 UTC, juanSTIC commented
- Si no eres administrador, el autor no pude ni clonar ni eliminar un informe (no aparecen los iconos)
-

2024-09-06 07:48 UTC, juanSTIC commented
- Se pierde el autor al abrir un informe si no eres administrador

2024-09-06 08:26 UTC, PaulaaSTIC requested changes
Ver comentarios.

2024-09-06 10:03 UTC, juanSTIC commented
> * Cambiar el filtro de tipos a lista desplegable y prescindir de los iconos

Hecho

2024-09-06 16:00 UTC, PaulaaSTIC requested changes
La URL que se genera desde el nuevo botón "Copiar URL pública" no incluye el segmento correspondiente al idioma (/en/es/ca/), lo que provoca un error.

2024-09-09 16:04 UTC, jortilles requested changes
Quitar el console.log y cambiar a homeSDA

2024-09-10 05:10 UTC, juanSTIC commented
Edición sugerida:
```diff
diff --git a/eda/eda_app/src/app/module/pages/sdareports/sdareports.component.css b/eda/eda_app/src/app/module/pages/homesda/homesda.component.css
similarity index 100%
rename from eda/eda_app/src/app/module/pages/sdareports/sdareports.component.css
rename to eda/eda_app/src/app/module/pages/homesda/homesda.component.css
diff --git a/eda/eda_app/src/app/module/pages/sdareports/sdareports.component.html b/eda/eda_app/src/app/module/pages/homesda/homesda.component.html
similarity index 100%
rename from eda/eda_app/src/app/module/pages/sdareports/sdareports.component.html
rename to eda/eda_app/src/app/module/pages/homesda/homesda.component.html
diff --git a/eda/eda_app/src/app/module/pages/sdareports/sdareports.component.scss b/eda/eda_app/src/app/module/pages/homesda/homesda.component.scss
similarity index 100%
rename from eda/eda_app/src/app/module/pages/sdareports/sdareports.component.scss
rename to eda/eda_app/src/app/module/pages/homesda/homesda.component.scss
diff --git a/eda/eda_app/src/app/module/pages/sdareports/sdareports.component.ts b/eda/eda_app/src/app/module/pages/homesda/homesda.component.ts
similarity index 99%
rename from eda/eda_app/src/app/module/pages/sdareports/sdareports.component.ts
rename to eda/eda_app/src/app/module/pages/homesda/homesda.component.ts
index c4429b18..6d73ceec 100644
--- a/eda/eda_app/src/app/module/pages/sdareports/sdareports.component.ts
+++ b/eda/eda_app/src/app/module/pages/homesda/homesda.component.ts
@@ -1,4 +1,4 @@
-import { GroupService } from "./../../../services/api/group.service";
+import { GroupService } from "../../../services/api/group.service";
 import { Component, OnInit } from "@angular/core";
 import { Router } from "@angular/router";
 import { AlertService, DashboardService, SidebarService, StyleProviderService } from "@eda/services/service.index";
@@ -8,11 +8,11 @@ import Swal from "sweetalert2";
 import * as _ from "lodash";
 
 @Component({
-  selector: "app-sdareports",
-  templateUrl: "./sdareports.component.html",
-  styleUrls: ["./sdareports.component.css"]
+  selector: "app-homesda",
+  templateUrl: "./homesda.component.html",
+  styleUrls: ["./homesda.component.css"]
 })
-export class SdareportsComponent implements OnInit {
+export class HomeSdaComponent implements OnInit {
   // Dashboard Management
   public dashController: EdaDialogController;
   public dss: any[];
diff --git a/eda/eda_app/src/app/module/pages/pages.module.ts b/eda/eda_app/src/app/module/pages/pages.module.ts
index 914c1df8..0d490802 100644
--- a/eda/eda_app/src/app/module/pages/pages.module.ts
+++ b/eda/eda_app/src/app/module/pages/pages.module.ts
@@ -44,7 +44,7 @@ import { CalculatedColumnDialogComponent } from './data-sources/data-source-deta
 import { UploadFileComponent } from './data-sources/data-source-detail/upload-file/upload-file.component';
 import { SaveAsDialogComponent } from './dashboard/saveAsDialog/save-as-dialog.component';
 import { EditStylesDialogComponent } from './dashboard/edit-styles-dialog/edit-styles.dialog.component';
-/*SDA CUSTOM*/ import { SdareportsComponent } from './sdareports/sdareports.component';
+/*SDA CUSTOM*/ import { HomeSdaComponent } from './homesda/homesda.component';
 import { GlobalFilterComponent } from './dashboard/global-filter/global-filter.component';
 
 
@@ -91,7 +91,7 @@ import { GlobalFilterComponent } from './dashboard/global-filter/global-filter.c
         DashboardMailDialogComponent,
         SaveAsDialogComponent,
         EditStylesDialogComponent,
-        /*SDA CUSTOM*/ SdareportsComponent,
+        /*SDA CUSTOM*/ HomeSdaComponent,
         /*SDA CUSTOM*/ AboutComponent
 
     ]
diff --git a/eda/eda_app/src/app/module/pages/pages.routes.ts b/eda/eda_app/src/app/module/pages/pages.routes.ts
index 9e11874f..5ad8d4e6 100644
--- a/eda/eda_app/src/app/module/pages/pages.routes.ts
+++ b/eda/eda_app/src/app/module/pages/pages.routes.ts
@@ -10,7 +10,7 @@ import { DsConfigWrapperComponent } from './data-sources/dsconfig-wrapper.compon
 import { DataSourceListComponent } from './data-sources/data-source-list/data-source-list.component';
 import { ModelSettingsComponent } from './model-settings/model-settings.component';
 
-/*SDA CUSTOM*/import { SdareportsComponent } from './sdareports/sdareports.component';
+/*SDA CUSTOM*/import { HomeSdaComponent } from './homesda/homesda.component';
 /*SDA CUSTOM*/ import { AboutComponent } from './about/about.component';
 
 
@@ -36,7 +36,7 @@ const pagesRoutes: Routes = [
     { path: 'alerts-management', component: AlertsManagementComponent, canActivate:[VerifyTokenGuard]},
     { path: 'mail-management', component: MailManagementComponent, canActivate:[VerifyTokenGuard]},
     /*SDA CUSTOM*/ { path: 'about', component: AboutComponent, canActivate: [VerifyTokenGuard] },
-    /*SDA CUSTOM*/ { path: 'home', component: SdareportsComponent, canActivate: [VerifyTokenGuard] },
+    /*SDA CUSTOM*/ { path: 'home', component: HomeSdaComponent, canActivate: [VerifyTokenGuard] },
     { path: '', redirectTo: 'home', pathMatch: 'full' }
 ];
 
diff --git a/eda/eda_app/src/app/module/pages/sdareports/sdareports.component.spec.ts b/eda/eda_app/src/app/module/pages/sdareports/sdareports.component.spec.ts
deleted file mode 100644
index 74550ca6..00000000
--- a/eda/eda_app/src/app/module/pages/sdareports/sdareports.component.spec.ts
+++ /dev/null
@@ -1,23 +0,0 @@
-import { ComponentFixture, TestBed } from '@angular/core/testing';
-
-import { SdareportsComponent } from './sdareports.component';
-
-describe('SdareportsComponent', () => {
-  let component: SdareportsComponent;
-  let fixture: ComponentFixture<SdareportsComponent>;
-
-  beforeEach(async () => {
-    await TestBed.configureTestingModule({
-      declarations: [ SdareportsComponent ]
-    })
-    .compileComponents();
-
-    fixture = TestBed.createComponent(SdareportsComponent);
-    component = fixture.componentInstance;
-    fixture.detectChanges();
-  });
-
-  it('should create', () => {
-    expect(component).toBeTruthy();
-  });
-});

```

2024-09-10 11:25 UTC, jalbaiges submitted a review, later dismissed
Cadenas revisadas. Si es necesario validar viéndolo en la instancia, solicitadme nueva revisión cuando esté desplegada la última versión.

2024-09-12 15:26 UTC, jalbaiges requested changes
Revisando la página de inicio en el interfaz de usuario:

1. En los filtros de etiquetas/grupos/tipos aparece un _placeholder_ en el buscador cuyo texto ("buscar etiqueta/grupo") debe de estar "hardcodeado" (o por lo menos son cadenas que no aparecen en los ficheros revisados).

2.  Por coherencia con los otros dos filtros, parece que el _placeholder_ del filtro de tipos debería ser "Buscar tipo".

3. En el menú de Acciones los iconos de abrir y clonar tienen _tooltip_ pero el de eliminar no lo tiene.

4. Al hacer "inline edit" del tipo aparece un botón para cancelar la edición cuyo texto también parece estar hardcodeado o, a lo mejor, no traducido al catalán en el fichero base de EDA si es que la cadena está ahí.

2024-09-13 09:01 UTC, jalbaiges approved these changes

2024-09-16 09:59 UTC, merged