Hotfix - APP - Restaurado de filtro no nulo en paneles
SinergiaTIC/SinergiaDA pull request #165
Opened 2024-06-15 05:05 UTC by jortilles

## Descripción del Cambio
Restaurado del filtro no nulo en los paneles

## Issue(s) resuelto(s)

- solves  https://github.com/SinergiaTIC/SinergiaDA/issues/147

## Pruebas a realizar para validar el cambio
Realizar un informe con un panel y hacer un filtro de no nulo ni vacio.

2024-06-17 05:14 UTC, juanSTIC requested changes
Al añadir un filtro del tipo **Nombre_2 is not_null_nor_empty**  se  construye mal la clausula WHERE del la query y da el siguiente error


```
node_sda       |   code: 'ER_BAD_FIELD_ERROR',
node_sda       |   errno: 1054,
node_sda       |   sqlState: '42S22',
node_sda       |   sqlMessage: "Unknown column 'sda_stic_events.id.stic_events_id1_c.name' in 'where clause'",
node_sda       |   sql: 'SELECT `sda_stic_events`.`name` as `Nombre`, `sda_stic_eventsstic_events_id_c`.`name` as `Nombre_1`, `sda_stic_eventsstic_events_id1_c`.`name` as `Nombre_2` \n' +
node_sda       |     'FROM sda_stic_events\n' +
node_sda       |     'inner JOIN `sda_stic_events` `sda_stic_eventsstic_events_id_c` ON  `sda_stic_events`.`stic_events_id_c`  =  `sda_stic_eventsstic_events_id_c`.`id` \n' +
node_sda       |     'inner JOIN `sda_stic_events` `sda_stic_eventsstic_events_id1_c` ON  `sda_stic_events`.`stic_events_id1_c`  =  `sda_stic_eventsstic_events_id1_c`.`id` \n' +
node_sda       |     'where 1 = 1 \n' +
node_sda       |     "and `sda_stic_events.id.stic_events_id1_c`.`name` is not null and `sda_stic_events.id.stic_events_id1_c`.`name` != ''\n" +
node_sda       |     'group by `sda_stic_events`.`name`, `sda_stic_eventsstic_events_id_c`.`name`, `sda_stic_eventsstic_events_id1_c`.`name`'
node_sda       | }
```

2024-06-17 05:47 UTC, jortilles commented
Hemos separdo los issues. Este es solo reltativo al filtro no nulo. Si usas una auto-relación en la consulta falla. Ese es el otro issue que estamos resolviendo.

2024-06-17 09:07 UTC, PaulaaSTIC requested changes
Los campos de tipo numérico con alguna agregación dan error al intentar filtrar valores no nulos. Este error no se produce en reporting.

![num_no_nulos](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/8b1803f9-7e20-47ab-8799-d274c3edd8f7)

2024-06-17 11:11 UTC, jortilles commented
> Los campos de tipo numérico con alguna agregación dan error al intentar filtrar valores no nulos. Este error no se produce en reporting.
> 
> ![num_no_nulos](https://private-user-images.githubusercontent.com/125350097/340245878-8b1803f9-7e20-47ab-8799-d274c3edd8f7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjE3MTksIm5iZiI6MTcxODYyMTQxOSwicGF0aCI6Ii8xMjUzNTAwOTcvMzQwMjQ1ODc4LThiMTgwM2Y5LTdlMjAtNDdhYi04Nzk5LWQyNzRjM2VkZDhmNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxMDUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmNhM2NiOThhMmQyYTI2NTE3NTI4ZmMzM2MyNTI2ZGYxNzBjMTJkMDU4MjljZjgyZjZiMDI1YjkwYWY2M2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eeIfIIZVh2BsyYPlE6iuogNj26ThPad_2YvGrbZDYUE) [ ![num_no_nulos](https://private-user-images.githubusercontent.com/125350097/340245878-8b1803f9-7e20-47ab-8799-d274c3edd8f7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjE3MTksIm5iZiI6MTcxODYyMTQxOSwicGF0aCI6Ii8xMjUzNTAwOTcvMzQwMjQ1ODc4LThiMTgwM2Y5LTdlMjAtNDdhYi04Nzk5LWQyNzRjM2VkZDhmNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxMDUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmNhM2NiOThhMmQyYTI2NTE3NTI4ZmMzM2MyNTI2ZGYxNzBjMTJkMDU4MjljZjgyZjZiMDI1YjkwYWY2M2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eeIfIIZVh2BsyYPlE6iuogNj26ThPad_2YvGrbZDYUE) ](https://private-user-images.githubusercontent.com/125350097/340245878-8b1803f9-7e20-47ab-8799-d274c3edd8f7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjE3MTksIm5iZiI6MTcxODYyMTQxOSwicGF0aCI6Ii8xMjUzNTAwOTcvMzQwMjQ1ODc4LThiMTgwM2Y5LTdlMjAtNDdhYi04Nzk5LWQyNzRjM2VkZDhmNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxMDUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmNhM2NiOThhMmQyYTI2NTE3NTI4ZmMzM2MyNTI2ZGYxNzBjMTJkMDU4MjljZjgyZjZiMDI1YjkwYWY2M2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eeIfIIZVh2BsyYPlE6iuogNj26ThPad_2YvGrbZDYUE) [ ](https://private-user-images.githubusercontent.com/125350097/340245878-8b1803f9-7e20-47ab-8799-d274c3edd8f7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjE3MTksIm5iZiI6MTcxODYyMTQxOSwicGF0aCI6Ii8xMjUzNTAwOTcvMzQwMjQ1ODc4LThiMTgwM2Y5LTdlMjAtNDdhYi04Nzk5LWQyNzRjM2VkZDhmNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxMDUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmNhM2NiOThhMmQyYTI2NTE3NTI4ZmMzM2MyNTI2ZGYxNzBjMTJkMDU4MjljZjgyZjZiMDI1YjkwYWY2M2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eeIfIIZVh2BsyYPlE6iuogNj26ThPad_2YvGrbZDYUE)

MmMm... claro con los números no tiene sentido.
Tenemos 3 opciones:
1. Los campos numéricos y de fecha no tienen las opciones "no nulo ni vacío"
2. Los campos numéricos y de fecha se hace un cast a string ( esto afecta al rendimiento )
3. Los campos numéricos y de fecha...  si llega un "no nulo ni vacío" se convierte a "no nulo" puesto que no tienen cadenas vacías '' 
Yo opto por la opción 3. Creo que es la mejor. Por favor. Confirmadme la decisión e implementamos eso. @PaulaaSTIC  @juanSTIC

2024-06-17 14:45 UTC, PaulaaSTIC commented
> > Los campos de tipo numérico con alguna agregación dan error al intentar filtrar valores no nulos. Este error no se produce en reporting.
> > ![num_no_nulos](https://private-user-images.githubusercontent.com/125350097/340245878-8b1803f9-7e20-47ab-8799-d274c3edd8f7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjE3MTksIm5iZiI6MTcxODYyMTQxOSwicGF0aCI6Ii8xMjUzNTAwOTcvMzQwMjQ1ODc4LThiMTgwM2Y5LTdlMjAtNDdhYi04Nzk5LWQyNzRjM2VkZDhmNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxMDUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmNhM2NiOThhMmQyYTI2NTE3NTI4ZmMzM2MyNTI2ZGYxNzBjMTJkMDU4MjljZjgyZjZiMDI1YjkwYWY2M2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eeIfIIZVh2BsyYPlE6iuogNj26ThPad_2YvGrbZDYUE)
> >       
> >         [
> >           
> >             ![num_no_nulos](https://private-user-images.githubusercontent.com/125350097/340245878-8b1803f9-7e20-47ab-8799-d274c3edd8f7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjE3MTksIm5iZiI6MTcxODYyMTQxOSwicGF0aCI6Ii8xMjUzNTAwOTcvMzQwMjQ1ODc4LThiMTgwM2Y5LTdlMjAtNDdhYi04Nzk5LWQyNzRjM2VkZDhmNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxMDUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmNhM2NiOThhMmQyYTI2NTE3NTI4ZmMzM2MyNTI2ZGYxNzBjMTJkMDU4MjljZjgyZjZiMDI1YjkwYWY2M2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eeIfIIZVh2BsyYPlE6iuogNj26ThPad_2YvGrbZDYUE)
> >           
> >         ](https://private-user-images.githubusercontent.com/125350097/340245878-8b1803f9-7e20-47ab-8799-d274c3edd8f7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjE3MTksIm5iZiI6MTcxODYyMTQxOSwicGF0aCI6Ii8xMjUzNTAwOTcvMzQwMjQ1ODc4LThiMTgwM2Y5LTdlMjAtNDdhYi04Nzk5LWQyNzRjM2VkZDhmNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxMDUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmNhM2NiOThhMmQyYTI2NTE3NTI4ZmMzM2MyNTI2ZGYxNzBjMTJkMDU4MjljZjgyZjZiMDI1YjkwYWY2M2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eeIfIIZVh2BsyYPlE6iuogNj26ThPad_2YvGrbZDYUE)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/125350097/340245878-8b1803f9-7e20-47ab-8799-d274c3edd8f7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjE3MTksIm5iZiI6MTcxODYyMTQxOSwicGF0aCI6Ii8xMjUzNTAwOTcvMzQwMjQ1ODc4LThiMTgwM2Y5LTdlMjAtNDdhYi04Nzk5LWQyNzRjM2VkZDhmNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxMDUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmNhM2NiOThhMmQyYTI2NTE3NTI4ZmMzM2MyNTI2ZGYxNzBjMTJkMDU4MjljZjgyZjZiMDI1YjkwYWY2M2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eeIfIIZVh2BsyYPlE6iuogNj26ThPad_2YvGrbZDYUE)
> >         
> >        [ ![num_no_nulos](https://private-user-images.githubusercontent.com/125350097/340245878-8b1803f9-7e20-47ab-8799-d274c3edd8f7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjE3MTksIm5iZiI6MTcxODYyMTQxOSwicGF0aCI6Ii8xMjUzNTAwOTcvMzQwMjQ1ODc4LThiMTgwM2Y5LTdlMjAtNDdhYi04Nzk5LWQyNzRjM2VkZDhmNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxMDUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmNhM2NiOThhMmQyYTI2NTE3NTI4ZmMzM2MyNTI2ZGYxNzBjMTJkMDU4MjljZjgyZjZiMDI1YjkwYWY2M2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eeIfIIZVh2BsyYPlE6iuogNj26ThPad_2YvGrbZDYUE) ](https://private-user-images.githubusercontent.com/125350097/340245878-8b1803f9-7e20-47ab-8799-d274c3edd8f7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjE3MTksIm5iZiI6MTcxODYyMTQxOSwicGF0aCI6Ii8xMjUzNTAwOTcvMzQwMjQ1ODc4LThiMTgwM2Y5LTdlMjAtNDdhYi04Nzk5LWQyNzRjM2VkZDhmNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxMDUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmNhM2NiOThhMmQyYTI2NTE3NTI4ZmMzM2MyNTI2ZGYxNzBjMTJkMDU4MjljZjgyZjZiMDI1YjkwYWY2M2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eeIfIIZVh2BsyYPlE6iuogNj26ThPad_2YvGrbZDYUE)
> >       
> >         [
> >           
> >             ![num_no_nulos](https://private-user-images.githubusercontent.com/125350097/340245878-8b1803f9-7e20-47ab-8799-d274c3edd8f7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjE3MTksIm5iZiI6MTcxODYyMTQxOSwicGF0aCI6Ii8xMjUzNTAwOTcvMzQwMjQ1ODc4LThiMTgwM2Y5LTdlMjAtNDdhYi04Nzk5LWQyNzRjM2VkZDhmNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxMDUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmNhM2NiOThhMmQyYTI2NTE3NTI4ZmMzM2MyNTI2ZGYxNzBjMTJkMDU4MjljZjgyZjZiMDI1YjkwYWY2M2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eeIfIIZVh2BsyYPlE6iuogNj26ThPad_2YvGrbZDYUE)
> >           
> >         ](https://private-user-images.githubusercontent.com/125350097/340245878-8b1803f9-7e20-47ab-8799-d274c3edd8f7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjE3MTksIm5iZiI6MTcxODYyMTQxOSwicGF0aCI6Ii8xMjUzNTAwOTcvMzQwMjQ1ODc4LThiMTgwM2Y5LTdlMjAtNDdhYi04Nzk5LWQyNzRjM2VkZDhmNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxMDUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmNhM2NiOThhMmQyYTI2NTE3NTI4ZmMzM2MyNTI2ZGYxNzBjMTJkMDU4MjljZjgyZjZiMDI1YjkwYWY2M2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eeIfIIZVh2BsyYPlE6iuogNj26ThPad_2YvGrbZDYUE)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/125350097/340245878-8b1803f9-7e20-47ab-8799-d274c3edd8f7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjE3MTksIm5iZiI6MTcxODYyMTQxOSwicGF0aCI6Ii8xMjUzNTAwOTcvMzQwMjQ1ODc4LThiMTgwM2Y5LTdlMjAtNDdhYi04Nzk5LWQyNzRjM2VkZDhmNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwN [...]

2024-06-18 04:52 UTC, jortilles commented
Hola.
He revisado los errores detectados ayer y creo que ahora ya está todo bien.
Podéis volver a revisar? 
Gracias.

2024-06-18 07:01 UTC, juanSTIC approved these changes
Verificadas las incidencias reportadas que ya funcionan bien.

2024-06-18 07:54 UTC, PaulaaSTIC approved these changes
(A)probado

2024-06-18 07:55 UTC, merged