Enhancement  -  API  - Aplicación indebida de permisos de grupo sobre tabla incorrecta
SinergiaTIC/SinergiaDA pull request #177
Opened 2024-07-01 15:57 UTC by jortilles

## Descripción del Cambio
En la actualidad SDA aplica los permisos sobre las tablas que se usan en las consultas y sobre todas las que estén relacionadas.

En el issue https://github.com/SinergiaTIC/SinergiaDA/issues/175 se pide que los permisos de seguridad se apliquen sólo a las tablas que aparecen en la consulta. Y este PR aplica este cambio.

## Issue(s) resuelto(s)

- solves  https://github.com/SinergiaTIC/SinergiaDA/issues/175

## Pruebas a realizar para validar el cambio
Realizar consultas sobre EDA con usuarios no administradores y revisar la correspondencia entre los permisos aplicados y los definidos en las tablas de configuración sda_def_XX

2024-07-02 10:15 UTC, PaulaaSTIC requested changes
**No se aplica la seguridad de módulos relacionados.**
Si creamos la consulta partiendo desde un módulo al que tenemos acceso total y luego vamos a módulos con permisos de grupo, no se aplica la condición de grupo.

![No_seguridad en campos relacionads](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/1a218dba-9174-4cda-a90a-b1e5edaf485c)

2024-07-08 14:27 UTC, jortilles commented
Es necesario volver a ejecutar update model

2024-07-09 14:36 UTC, PaulaaSTIC requested changes
**Paneles sin acceso:**

Si un usuario no administrador accede a un informe donde el módulo principal de un panel es un módulo al que no tenemos acceso, deberíamos mostrar un mensaje indicando que no se tiene acceso a los datos. Podríamos hacerlo con un mensaje en el panel: "Este panel no está disponible por falta de permisos". Esto debe ocurrir tanto si en el panel solo aparecen campos de este módulo como si aparecen de otros módulos a los que sí tenemos acceso. Si el módulo principal no es visible para nosotros, debe aparecer dicho mensaje, ya que la consulta no se puede cargar correctamente. Actualmente, hay un comportamiento diferente que puede generar confusión.

2024-07-10 09:11 UTC, PaulaaSTIC approved these changes

2024-07-10 09:11 UTC, juanSTIC approved these changes

2024-07-10 09:12 UTC, merged