Hotfix- API - Incorporación incompleta de permisos a nivel de usuario en el modelo de datos tras ejecutar updateModel. - Sda#133
SinergiaTIC/SinergiaDA pull request #178
Opened 2024-07-01 16:03 UTC by jortilles

## Descripción del Cambio
Al ejecutar el updateModel no se crean permisos de usuario dinámicos en función de la pertenencia de los registros.
Se modifica el update model para que genere estos permisos.

## Issue(s) resuelto(s)

- solves  https://github.com/SinergiaTIC/SinergiaDA/issues/133

## Pruebas a realizar para validar el cambio
Ejecutar el updateModel y tras  aplicar el PR https://github.com/SinergiaTIC/SinergiaDA/pull/177 comprobar el correcto funcionamiento realizando consultas con un usuario que tenga permisos sobre registros en las tablas de configuración sda_def_XXX

2024-07-02 12:40 UTC, PaulaaSTIC requested changes
Los filtros deben incluirse a los anteriores con lógica **OR**, pero actualmente se están aplicando con AND.


```
SELECT `sda_stic_assessments`.`conclusions` as `Conclusiones`, `sda_stic_assessments`.`working_with` as `En coordinación con`  
FROM sda_stic_assessments 
and (`sda_stic_attendances`.`id`  in ('select record_id from sda_def_security_group_records where `group` =  ''SDA_G1''  and `table` =  ''sda_stic_attendances'' ')  )  
and (`sda_stic_sepe_actions`.`id`  in ('select record_id from sda_def_security_group_records where `group` =  ''SDA_G1''  and `table` =  ''sda_stic_sepe_actions'' ')  )  
and (`sda_stic_sepe_actions`.`assigned_user_name`  in ('select `assigned_user_name` from sda_stic_sepe_actions where `assigned_user_name` = ''u1'' ')  )  
and (`sda_stic_attendances`.`assigned_user_name`  in ('select `assigned_user_name` from sda_stic_attendances where `assigned_user_name` = ''u1'' ')  )  
and (`sda_stic_assessments`.`assigned_user_name`  in ('select `assigned_user_name` from sda_stic_assessments where `assigned_user_name` = ''u1'' ')  )  
group by `sda_stic_assessments`.`conclusions`, `sda_stic_assessments`.`working_with`

```

2024-07-10 09:54 UTC, jortilles commented
Hay que revisar los wheres que vienen de consulta y los de los filtros de seguridad. Consulta => AND Filtro => OR

2024-07-18 08:50 UTC, PaulaaSTIC requested changes
Sigue apareciendo con **AND** la consulta:
```
SELECT `sda_stic_assessments`.`conclusions` as `Conclusiones`, `sda_stic_assessments`.`working_with` as `En coordinación con`  
FROM sda_stic_assessments 
**and** (`sda_stic_attendances`.`id`  in ('select record_id from sda_def_security_group_records where `group` =  ''SDA_G1''  and `table` =  ''sda_stic_attendances'' ')  )  
**and** (`sda_stic_attendances`.`assigned_user_name`  in ('select `assigned_user_name` from sda_stic_attendances where `assigned_user_name` = ''u1'' ')  )  

```

2024-07-18 10:47 UTC, juanSTIC requested changes
Además de lo indicado por @PaulaaSTIC es importante el siguiente detalle:
Cuando se añade una condición de seguridad no solo es importante que se utilice el operador **OR**, sino que es imprescindible que este s**e aplique como parte de la misma condición del grupo de seguridad**, tal como se muestra en el segundo ejemplo, de lo contrario solo se mostrarán los registros que cumplan ambas condiciones:
```sql
-- FORMATO ACTUAL INCORRECTO
SELECT `sda_contacts`.`first_name` as `Nombre`  
	FROM sda_contacts 
where  
	(`sda_contacts`.`id`  in (select record_id from sda_def_security_group_records where `group` =  'SDA_G1'  and `table` =  'sda_contacts' )  )  
	and (`sda_contacts`.`assigned_user_name`  in (select `assigned_user_name` from sda_contacts where `assigned_user_name` = 'u1' )  )  


-- FORMATO ESPERADO CORRECTO
SELECT `sda_contacts`.`first_name` as `Nombre`  
	FROM sda_contacts 
WHERE  	(
			(`sda_contacts`.`id`  in (select record_id from sda_def_security_group_records where `group` =  'SDA_G1'  and `table` =  'sda_contacts' ) )   
			OR 
			(`sda_contacts`.`assigned_user_name`  in (select `assigned_user_name` from sda_contacts where `assigned_user_name` = 'u1' )  )  
	    )

```

2024-07-23 15:25 UTC, jortilles commented
Console logs limpios y botón de filtrar repuesto

2024-07-23 16:00 UTC, juanSTIC approved these changes
Visto y probado

2024-07-31 12:51 UTC, PaulaaSTIC approved these changes
(A)probado

2024-08-19 08:46 UTC, merged