Hotfix - APP - Se duplican tablas en el modo árbol - SDA#180
SinergiaTIC/SinergiaDA pull request #181
Opened 2024-07-09 05:44 UTC by jortilles

## Descripción del Cambio
Cuando se aplica la seguridad. Es necesario filtrar el modelo de datos para las tablas visibles. y quitar las auto-relaciones cuando se regenera el listado de tablas

## Issue(s) resuelto(s)
- solves  #180 

## Pruebas a realizar para validar el cambio
Hacer un informe con un usuario no administrador. Generar una consulta con auto-relaciones y borrarla. Cuando se vuelve a mostrar el listado de tablas. Ahora es correcto.

2024-07-09 08:46 UTC, PaulaaSTIC commented
Las tablas no se duplican, pero se desordenan.
Se produce tanto en usuarios administradores como en usuarios no administradores.

![Desorden tablas](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/5188a07c-7675-4b98-8570-e2452b2e334b)

2024-07-09 08:48 UTC, PaulaaSTIC requested changes
Las tablas no se duplican, pero se desordenan.
Se produce tanto en usuarios administradores como en usuarios no administradores.

![Desorden tablas](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/5188a07c-7675-4b98-8570-e2452b2e334b)

2024-07-09 10:35 UTC, jortilles commented
@ronaldchavezjortilles  ya ha hecho la ordenación.

2024-07-09 11:09 UTC, PaulaaSTIC approved these changes
(A)probado

2024-07-10 08:56 UTC, juanSTIC approved these changes

2024-07-10 08:56 UTC, merged