Feature - APP - Visualización de paneles con seguridad y sin datos
SinergiaTIC/SinergiaDA pull request #188
Opened 2024-07-12 13:43 UTC by jortilles

## Descripción del Cambio
Si la api devuelve  "no data allowed" el panel muestra un mensaje de "Este panel no está disponible por falta de permisos"

## Issue(s) resuelto(s)
- solves #182 

## Pruebas a realizar para validar el cambio
Hacer un informe con un panel con una consulta  con una tabla en la que haya permisos y acceder con un usuario que no tenga permiso.

2024-07-12 14:20 UTC, juanSTIC requested changes
Funciona correctamente. Revisar comentario

2024-07-12 14:20 UTC, juanSTIC commented on eda/eda_app/src/app/module/components/eda-panels/eda-blank-panel/panel-utils/query-utils.ts
> +        err.text =  $localize`:@@noPermitsAlert:No tiene acceso a una o varias de las tablas de la consulta`
¿Este código se utiliza? No he visto que aparezca en ningún log ni tampoco están las traducciones de la cadena

2024-07-13 06:29 UTC, jortilles commented on eda/eda_app/src/app/module/components/eda-panels/eda-blank-panel/panel-utils/query-utils.ts
> +        err.text =  $localize`:@@noPermitsAlert:No tiene acceso a una o varias de las tablas de la consulta`
Tienes razón. Esas lineas se me han "colado". No tienen utilidad.
Ya las he quitado.

2024-07-15 06:18 UTC, juanSTIC submitted a review, later dismissed
Visto y probado

2024-07-15 08:33 UTC, PaulaaSTIC requested changes
Si el informe contiene un filtro de una tabla sobre la cual no tenemos permisos, el informe se queda congelado, no se cargan los paneles sobre los que no actúa el filtro y no se puede realizar ninguna acción.
![permisos_filtros](https://github.com/user-attachments/assets/b111920e-5e72-4af5-ae0f-2b9f15dabbeb)

2024-07-15 16:07 UTC, jortilles commented
<img width="941" alt="image" src="https://github.com/user-attachments/assets/684e5083-3add-4e4a-88d8-e29800bdc736">

Si un panel está filtrado por un campo al que no tengo acceso se muestra un mensaje parecido al de no data allowed pero especifico.

Si un flitro no muestra valores por un filtro de seguridad se informa (si es posible.)

2024-07-17 14:54 UTC, ronaldchavezjortilles commented
Ya se puede volver a revisar que **no** se mostrara el desplegable de los filtros si el usuario no tiene permisos.

2024-07-18 08:51 UTC, PaulaaSTIC requested changes
El filtro aparece de la siguiente forma:
![image](https://github.com/user-attachments/assets/52451b79-fc6c-407c-86e1-1287838de5fc)

2024-07-18 14:57 UTC, ronaldchavezjortilles commented
Ya se pudo verificar los cambios, de que no se muestre los filtros para usuarios que no tienen los permisos adecuados.

2024-07-24 07:45 UTC, juanSTIC approved these changes
Aprobado

2024-08-06 09:54 UTC, jortilles commented
El comportamiento ya es el deseado.

2024-08-19 10:45 UTC, PaulaaSTIC approved these changes
(A)Probado

2024-08-19 11:52 UTC, jalbaiges approved these changes
Cadenas revisadas

2024-08-23 10:30 UTC, juanSTIC approved these changes

2024-09-03 08:55 UTC, merged