Incidencia - API - Respetar pertenencia a grupos al  ejecutar updateModel
SinergiaTIC/SinergiaDA pull request #211
Opened 2024-09-26 11:20 UTC by juanSTIC

## Descripción del Cambio

## Issue(s) resuelto(s)

- solves 

## Pruebas a realizar para validar el cambio

## Información Adicional

2024-09-30 09:37 UTC, PaulaaSTIC requested changes
**Error con los permisos del CRM:**
No se actualiza la membresía de usuarios de SCRM a grupos de SCRM, teniendo un usuario con los siguientes grupos, como u3:
 ![image](https://github.com/user-attachments/assets/84dc5d8d-cc9c-46b1-a791-bded6cb9713b)
Al ejecutar el updateModel, no se actualizan los grupos a los que pertenece.
![image](https://github.com/user-attachments/assets/8baf6485-1da0-4ca9-a580-0ead2238c606)
En la rama reporting, no se produce este comportamiento.

2024-09-30 09:49 UTC, juanSTIC commented
Hay un error al eliminar un grupo de usuarios en el CRM y ejecutar updateModel, si este contenía algún usuario de EDA: el  usuario pierde todos los grupos (al menos en la interfaz) no se ven y se muestra lo siguiente:
![image](https://github.com/user-attachments/assets/34dd0d81-e8f3-46cb-aa1e-40bb96cdc1d0)

Aunque si se edita el usuario y se guarda, los grupos vuelven a aparecer.

2024-10-02 10:16 UTC, PaulaaSTIC approved these changes
(A)probado

2024-10-02 15:09 UTC, jortilles approved these changes

2024-10-04 05:48 UTC, merged