Hotfix - API+APP  - Mantener los permisos de usuario asignados Mostrar número de puerto correcto al arrancar api
SinergiaTIC/SinergiaDA pull request #215
Opened 2024-10-03 05:04 UTC by jortilles

## Descripción del Cambio
Cuando se crea un permiso desde el fornt-end se le añade una etiqueta source: 'SDA' que nos permite identificar que permisos vienen del front-end

## Issue(s) resuelto(s)

- solves #208

## Pruebas a realizar para validar el cambio
Añadir permisos desde el front-end de SDA, ejecutar el update-model y comprobar que siguen ahi.

2024-10-03 10:48 UTC, juanSTIC approved these changes
No funciona, el código no hace los esperado.

2024-10-03 10:48 UTC, juanSTIC requested changes
No funciona

2024-10-07 10:05 UTC, jortilles commented
El problema es que el comportamiento que describes se solucionaba en el pr https://github.com/SinergiaTIC/SinergiaDA/pull/211   por eso aqui no funcionaba. 
He mergeado reporting en este pr y  ahora ya vuelve a funcionar bien.

2024-10-07 12:08 UTC, PaulaaSTIC approved these changes
(A)probado

2024-10-08 14:37 UTC, juanSTIC approved these changes
Visto y probado

2024-10-08 14:39 UTC, merged