Improvement - APP - No es posible crear tablas cruzadas si una de las dimensiones es un número
SinergiaTIC/SinergiaDA pull request #228
Opened 2024-10-11 16:08 UTC by jortilles

## Descripción del Cambio
Se ha refactorizado todo lo relacionado con la generación de las tablas cruzadas para poder elegir la visualización que se desee. Ahora se puede elegir qué quieres ver en las columnas y en las filas. Independientemente de si son  números o textos.

## Issue(s) resuelto(s)
- solves #77

## Pruebas a realizar para validar el cambio
Realizar tablas cruzadas y jugar con la configuración.
Adicionalmente se ha tenido que revisar todos los componentes extras: Totales, porcentajes, tendencias, etc.

2024-10-22 08:40 UTC, juanSTIC requested changes
La gestión de nuevas tablas cruzadas parece funcionar sin problema (habrá que hacer más pruebas), sin embargo las tablas cruzadas previamente existentes da error. Para muestra el siguiente informe descargado, funciona correctamente en la rama reporting, pero falla en la nueva rama dragAndDrop
[dashboard (4).json](https://github.com/user-attachments/files/17472918/dashboard.4.json)

2024-10-22 09:49 UTC, juanSTIC commented
@ronaldchavezjortilles  se acuerda lo siguiente sobre este PR:

1. Debe poderse mostrar la tabla cruzada siempre que haya al menos tres campos, independientemente de su tipo. Ahora no se puede.
2. Si alguno de los campos usados en el área de resultados no está agregado se usa automáticamente la agregación suma.
3. Debe mostrarse una leyenda en cada una de las áreas con texto explicativos sobre su función. En la del área de resultados informar que _suma_ es la agregación por defecto si el un campo no viene pre-agregado.

2024-10-25 10:54 UTC, ronaldchavezjortilles commented
Issues y modificaciones resueltas

2024-11-19 05:48 UTC, jortilles commented
Funciona correctamente

2024-11-29 09:08 UTC, PaulaaSTIC requested changes
No se muestra leyenda sobre el funcionamiento de las tablas cruzadas.

Cuando se tienen tres campos de tipo texto, aunque la opción de tablas cruzadas no está disponible, es posible seleccionarla y se muestra el cuadro de configuración de la tabla.

2024-12-11 09:09 UTC, PaulaaSTIC approved these changes
Visto y probado

2024-12-17 08:48 UTC, jortilles commented
Hola. Esto esta listo para que lo probéis.

2024-12-20 11:03 UTC, PaulaaSTIC submitted a review, later dismissed
(A)probado

2024-12-23 15:04 UTC, juanSTIC requested changes
Cuando hay más de un campo en el eje horizontal, no es posible elegir_Código de color_, ya que el desplegable no muestra nada:
![image](https://github.com/user-attachments/assets/abd524e1-e1b2-4e66-9744-d7d64caf38bb)

2024-12-23 15:53 UTC, juanSTIC requested changes
ver comentarios

2024-12-23 15:53 UTC, juanSTIC commented on eda/eda_app/src/app/module/components/eda-table/eda-table.ts
> +        // VERIFICAR SI SE RELLENAN CON CEROS LOS VALORES QUE LLEGAN VACIOS
si este código no se utiliza, quitarlo

2025-01-10 14:46 UTC, jortilles commented on eda/eda_app/src/app/module/components/eda-table/eda-table.ts
> +        // VERIFICAR SI SE RELLENAN CON CEROS LOS VALORES QUE LLEGAN VACIOS
Quitado

2025-01-10 14:52 UTC, jortilles commented
Visto y revisado

2025-01-13 17:03 UTC, juanSTIC approved these changes
Visto y probado

2025-01-14 10:22 UTC, PaulaaSTIC approved these changes
(A)probado

2025-01-14 16:01 UTC, merged