Hotfix- API - Permisos de grupo restringen acceso a usuarios que no deberían tener restricción de grupo
SinergiaTIC/SinergiaDA pull request #234
Opened 2024-10-18 09:33 UTC by jortilles

## Descripción del Cambio

Ahora los pemisos de grupo se aplican a nivel de usuario  si así lo está especificado.  

## Issue(s) resuelto(s)
- solves #232

## Pruebas a realizar para validar el cambio
Se realiza el cambio, se hace un update model y se ve que el comportamiento es el esparado.

A nivel de modelo tengo:

 {
                    "users": [
                        "663e24aa0c13814890c2ada0"
                    ],
                    "usersName": [
                        "u3"
                    ],
                    "none": false,
                    "table": "sda_stic_sepe_actions",
                    "column": "id",
                    "dynamic": true,
                    "global": false,
                    "type": "users",
                    "value": [
                        "select record_id from sda_def_security_group_records where `group` =  'SCRM_G3'  and `table` =  'sda_stic_sepe_actions' "
                    ],
                    "source": "update_model"
                },

que es un permiso de usuario y eso se traduce en una consulta del tipo 

SELECT cast(sum(`sda_stic_sepe_actions`.`N`) as decimal(32,0) ) as `(n) Acciones SEPE`, `sda_l_stic_sepe_actions_agreement_stic_sepe_agreement_list`.`value` as `Convenio`
FROM sda_stic_sepe_actions
LEFT JOIN `sda_l_stic_sepe_actions_agreement_stic_sepe_agreement_list` ON  `sda_stic_sepe_actions`.`agreement` = `sda_l_stic_sepe_actions_agreement_stic_sepe_agreement_list`.`code`
where 1 = 1
and ( `sda_stic_sepe_actions`.`id`  in (select record_id from sda_def_security_group_records where `group` =  'SCRM_G3'  and `table` =  'sda_stic_sepe_actions' )
  or `sda_stic_sepe_actions`.`assigned_user_name`  in (select `assigned_user_name` from sda_stic_sepe_actions where `assigned_user_name` = 'u3' )
  )
group by `sda_l_stic_sepe_actions_agreement_stic_sepe_agreement_list`.`value`
order by `(n) Acciones SEPE` Desc

2024-10-20 07:22 UTC, jortilles commented
Ya se puede validar

2024-10-21 08:47 UTC, juanSTIC requested changes
Los permisos de grupo definidos en sda_def_permissions se trasladan incompletos  al modelo de datos
Por ejemplo, para los siguientes permisos en sda_def_permissions...
![image](https://github.com/user-attachments/assets/fd63ce8b-66b9-460d-b885-b9b172b01d00)

...los permisos que se crean en el modelo de datos son:
![image](https://github.com/user-attachments/assets/02abf01b-2f3a-4644-9cda-13897d2304d3)

2024-10-22 08:18 UTC, PaulaaSTIC commented
Los permisos de grupo se trasladan correctamente, pero no se están trasladando los permisos ALLOW_ALL de visibilidad total de tablas. El problema lo encontramos tanto si el usuario solo tiene permisos ALLOW_ALL para las tablas, o si tiene parte de grupo parte todo. 
Antes en el apartado 
 
![image](https://github.com/user-attachments/assets/2f25fd18-e6f3-4df7-80e4-91558a723493)

2024-10-22 08:25 UTC, PaulaaSTIC requested changes
Los permisos de grupo se trasladan bien, pero los permisos ALLOW_ALL de visibilidad total de tablas no se están aplicando. El problema se presenta tanto cuando el usuario tiene solo permisos ALLOW_ALL para las tablas, como cuando los permisos son combinados entre el grupo y ALLOW_ALL.

Antes, en el apartado de Visibilidad de Tablas, se mostraban los grupos (ahora no aparecen, lo cual está bien), pero deberían seguir apareciendo los usuarios que tienen acceso a una tabla específica.

 
![image](https://github.com/user-attachments/assets/9df7e78b-6e26-466c-a243-7e520f76bdbd)
Ahora, aunque el acceso está definido en sda_def_columns, no se refleja en el modelo.

![image](https://github.com/user-attachments/assets/2f25fd18-e6f3-4df7-80e4-91558a723493)
![image](https://github.com/user-attachments/assets/e23e364a-52bb-47a9-888a-1c150749faba)

2024-10-22 14:35 UTC, juanSTIC approved these changes
Se ha comprobado que los permisos se añaden correctamente para cada usuario y no a nivel de grupo.

2024-10-22 14:36 UTC, PaulaaSTIC approved these changes

2024-10-22 14:48 UTC, merged