Enhancement- EDA - SDA - Seguridad aplicada a módulos relacionados limita la visibilidad de registros
SinergiaTIC/SinergiaDA pull request #235
Opened 2024-10-18 09:47 UTC by jortilles

## Descripción del Cambio
Se ha visto que cuando aplica seguridad. En el modo normal en el que se hacen las consultas no se resuelven bien los left joins.
Una vez aplicado el cambio el comportamiento es el descrito en el issue.

## Issue(s) resuelto(s)

- solves  #200

## Pruebas a realizar para validar el cambio
Realizar consultas con filtros de seguridad y filtros de informe y ver que el comportamiento es el esperado.
si hay más de una tabla. Los filtros de seguridad se adjuntan al join y los filtros del informe al where.

2024-10-21 09:18 UTC, PaulaaSTIC requested changes
No se me está aplicando la seguridad correctamente. En esta rama, la consulta que se ejecuta es la siguiente:

```
SELECT `sda_accounts`.`name` as `Nombre`, cast(sum(`sda_stic_payment_commitments`.`amount`) as decimal(32,2) ) as `Importe`  
FROM sda_accounts 
inner JOIN `sda_stic_payment_commitments` ON  `sda_accounts`.`id` = `sda_stic_payment_commitments`.`stic_payment_commitments_accountsaccounts_ida`  
and ( `sda_stic_payment_commitments`.`id`  in (select record_id from sda_def_security_group_records where `group` =  'SCRM_G2'  and `table` =  'sda_stic_payment_commitments' )  
  or `sda_stic_payment_commitments`.`id`  in (select record_id from sda_def_security_group_records where `group` =  'SCRM_G1'  and `table` =  'sda_stic_payment_commitments' )  
  or `sda_stic_payment_commitments`.`assigned_user_name`  in (select `assigned_user_name` from sda_stic_payment_commitments where `assigned_user_name` = 'u1' )  
  )  
group by `sda_accounts`.`name` 
order by `Importe` Desc
```
En esta consulta no se incluye la seguridad sobre el módulo principal. Mientras que si voy a reporting, la consulta que se ejecuta, incluye la inyección de seguridad:


```
SELECT `sda_accounts`.`name` as `Nombre`, cast(sum(`sda_stic_payment_commitments`.`amount`) as decimal(32,2) ) as `Importe`  
FROM sda_accounts 
inner JOIN `sda_stic_payment_commitments` ON  `sda_accounts`.`id` = `sda_stic_payment_commitments`.`stic_payment_commitments_accountsaccounts_ida`  
where  ( `sda_stic_payment_commitments`.`id`  in (select record_id from sda_def_security_group_records where `group` =  'SCRM_G2'  and `table` =  'sda_stic_payment_commitments' )  
  or `sda_stic_payment_commitments`.`id`  in (select record_id from sda_def_security_group_records where `group` =  'SCRM_G1'  and `table` =  'sda_stic_payment_commitments' )  
  or `sda_stic_payment_commitments`.`assigned_user_name`  in (select `assigned_user_name` from sda_stic_payment_commitments where `assigned_user_name` = 'u1' )  
  )  
and ( `sda_accounts`.`id`  in (select record_id from sda_def_security_group_records where `group` =  'SCRM_G2'  and `table` =  'sda_accounts' )  
  or `sda_accounts`.`id`  in (select record_id from sda_def_security_group_records where `group` =  'SCRM_G1'  and `table` =  'sda_accounts' )  
  or `sda_accounts`.`assigned_user_name`  in (select `assigned_user_name` from sda_accounts where `assigned_user_name` = 'u1' )  
  )  
group by `sda_accounts`.`name` 
order by `Importe` Desc```

2024-10-21 10:19 UTC, juanSTIC requested changes
No funciona correctamente y no aplica la seguridad sobre el módulo principal en el WHERE.

Además se ha visto que se hay un agujero de seguridad si se utiliza RIGHT JOIN, ya que se permite que el usuario vea todos los registros del módulo (o los módulos de la derecha), por lo que la sugerencia es desactivar RIGHT JOIN

2024-10-21 16:24 UTC, juanSTIC commented
Se opta por ocultar el botón Right JOIN
y se pide poner un tooltip en los botones INNER JOIN y LEFT JOIN con los textos:
INNER JOIN: Solo se mostrarán los registros relacionados en ambas tablas a los que el usuario tenga acceso.
LEFT_JOIN: Se mostrarán todos los registros de la tabla principal a los que el usuario tenga acceso, y los registros relacionados del resto de tablas

2024-11-05 10:12 UTC, jortilles commented
@ronaldchavezjortilles

2024-11-13 05:26 UTC, jortilles commented
El comportamiento es el esperado

2024-12-11 12:40 UTC, PaulaaSTIC requested changes
Veo que se ha eliminado el join solicitado, pero no aparece el tooltip con la descripción del uso de las opciones que se muestran.

Al realizar las pruebas, se ha reproducido el error [#204](https://github.com/SinergiaTIC/SinergiaDA/issues/204). He comprobado que esta incidencia parece estar siendo resuelta en la rama SDA#204_v2, pero no encuentro el PR con estos cambios.

2024-12-23 13:02 UTC, juanSTIC requested changes
Ver comentario

2025-01-13 14:29 UTC, juanSTIC commented on eda/eda_api/lib/services/query-builder/query-builder.service.ts
> +/* esto no deberíamos hacerlo. */
borrado

2025-01-13 15:56 UTC, PaulaaSTIC approved these changes
(A)probado

2025-01-14 16:02 UTC, merged