Feature - API+APP - Posibilidad de crear tramos
SinergiaTIC/SinergiaDA pull request #254
Opened 2024-11-19 16:25 UTC by jortilles

## Descripción del Cambio
Se añade la posibilidad poder definir  rangos de valores sobre un campo numérico. El campo se convierte en un campo de texto. Los rangos se pueden editar.

## Issue(s) resuelto(s)
- solves #51

## Pruebas a realizar para validar el cambio
Realizar un panel con un campo numérico y definir rangos.

2024-11-29 09:20 UTC, PaulaaSTIC requested changes
1. En la imagen 1 se muestra el resumen de los tramos, mientras que en la imagen 2, al ejecutarse, cambia la simbología. En el resultado final (imagen 2) deberían aparecer los tramos especificados en la imagen 1.
2. No se puede modificar ni eliminar el rango implementado. Una vez aplicado, sería necesario quitar el campo y volver a añadirlo.

1-
![image](https://github.com/user-attachments/assets/2a94eb45-2c1c-445f-bf0a-ce7cf05e9f8f)
2-
![image](https://github.com/user-attachments/assets/c4483ea8-5781-44b5-96dc-2bfb54f7298c)

2024-12-16 18:47 UTC, jortilles commented
@ronaldchavezjortilles  falta revisar la ordenacion

2024-12-19 12:11 UTC, jortilles commented
Ya se han resuelto los casos encontrados. Ya se puede volver a validar

2024-12-20 08:27 UTC, PaulaaSTIC requested changes
```
SELECT   CASE 
	WHEN sda_stic_payment_commitments.amount < 12 THEN '< 12' 
	WHEN sda_stic_payment_commitments.amount >= 12 AND sda_stic_payment_commitments.amount <= 14 THEN ' 12 - 14' 
	WHEN sda_stic_payment_commitments.amount >= 15 AND sda_stic_payment_commitments.amount <= 17 THEN ' 15 - 17' 
	WHEN sda_stic_payment_commitments.amount >= 18 THEN '>= 18' 
END  as `Importe`  
FROM sda_stic_payment_commitments 
group by  CASE 
	WHEN sda_stic_payment_commitments.amount < 12 THEN '< 12' 
	WHEN sda_stic_payment_commitments.amount >= 12 AND sda_stic_payment_commitments.amount <= 14 THEN ' 12 - 14' 
	WHEN sda_stic_payment_commitments.amount >= 15 AND sda_stic_payment_commitments.amount <= 17 THEN ' 15 - 17' 
	WHEN sda_stic_payment_commitments.amount >= 18 THEN '>= 18' 
END  
order by CASE 
	WHEN sda_stic_payment_commitments.amount < 12 THEN 1 
	WHEN sda_stic_payment_commitments.amount >= 12 AND sda_stic_payment_commitments.amount <= 14 THEN 2 
	WHEN sda_stic_payment_commitments.amount >= 15 AND sda_stic_payment_commitments.amount <= 17 THEN 3 
	WHEN sda_stic_payment_commitments.amount >= 18 THEN  4 
END **No**
```

Al ejecutar la SQL el **No** que se escribe después  del último END genera un error de SQL, `Error quering database`

2024-12-23 08:53 UTC, juanSTIC requested changes
Error en la ordenación de los tramos
Aunque en la imagen que aparece al diseñar el tramo se muestra correctamente, en la consulta no aparecen ordenadas,  a pesar de que el campo esté ordenado (en este caso por importe):
![image](https://github.com/user-attachments/assets/a5226da6-c3b4-445e-93fe-424a71ec4944)


![image](https://github.com/user-attachments/assets/8759f485-c8fd-4701-a67d-7ebab1a73fd0)

2025-01-21 10:21 UTC, jortilles commented
Queda ordenar en el frontend y resolver los conflictos

2025-01-22 08:51 UTC, PaulaaSTIC submitted a review, later dismissed
(A)probado. Funciona la ordenación sin problema con números positvos

2025-01-27 20:17 UTC, jalbaiges requested changes
Revisadas las cadenas en _ca_, _en_ y _es_. Ver comentario sobre fichero en _pl_. En _gl_ se usa tanto rango como intervalo en unas u otras cadenas, debería usarse siempre el mismo término.

2025-01-28 15:43 UTC, jortilles commented on eda/eda_app/src/locale/messages.pl.xlf
No. Lo quito

2025-01-29 06:04 UTC, jortilles commented
Ronald me comenta que será un poco más largo hacerlo en las tablas cruzadas. Por eso os recomiendo cerrar este PR y tratarlo como una petición nueva la posibilidad de ordenar las tablas cruzadas de forma personalizada para los rangos.

2025-01-29 06:04 UTC, jortilles commented
Podéis volver a validar y cerrar este PR si queréis.

2025-01-29 09:30 UTC, juanSTIC approved these changes

2025-01-29 09:30 UTC, juanSTIC submitted a review, later dismissed
Visto y probado

2025-01-29 09:39 UTC, juanSTIC commented
> En _gl_ se usa tanto rango como intervalo en unas u otras cadenas, debería usarse siempre el mismo término.

Se cambian a "rango" en todos los casos de Galego

2025-01-29 09:39 UTC, juanSTIC approved these changes
reaprobado

2025-01-29 13:11 UTC, jalbaiges submitted a review, later dismissed

2025-01-29 14:57 UTC, PaulaaSTIC submitted a review, later dismissed
(A)probado

2025-01-29 15:00 UTC, PaulaaSTIC approved these changes
(A)probado

2025-01-29 15:39 UTC, juanSTIC approved these changes
Aprobado

2025-01-29 15:39 UTC, merged