Enhancement - API - Establecer límite de tiempo al ejecutar consultas
SinergiaTIC/SinergiaDA pull request #256
Opened 2024-11-28 09:13 UTC by juanSTIC

Se ha visto que cuando se ejecuta una query que tarda mucho tiempo puede afectar negativamente a la instancias de SinergiaCRM,por el hecho de que quede la query colgada y pueda afectar a otros procesos de iserción o modificación de registros de SinergiaCRM
Para evitarlo en las conexiones MariaDB/MySQL se establece un límite de 60 segundos para la ejecución de cualquier query individual, entendiendo que ninguna consulta (panel o filtro) en SinergiaDA pueda tardar más de este tiempo.

**Cómo probarlo**
- Preparar queries que sean especialmente pesadas, se pueden forzar creando consultas SQL del tipo `SELECT id,sleep(10) from sda_contacts`, lo que demorará la consulta el tiempo suficiente para alcanzar el límite de 60 segundos.
- Verificar que la consulta se cierra automáticamente al alcanzar este tiempo y no queda resto de ella al ejecutar `SHOW processlists`

2024-12-16 11:35 UTC, AlbertoSTIC requested changes
La librería de node mysql2 incluye un parámetro para especificar el timeout a las queries que se lanzar en la misma conexión. En este fichero de ejemplo se puede ver el siguiente código: https://github.com/sidorares/node-mysql2/pull/1364/files#diff-cb3d05309ca6ab9373e3079c7730dfbf9307c6d6d2f65abcab78e83000c9f992

```
const connection = common.createConnection({ 
  host: '10.255.255.1',
  debug: false,
  connectTimeout: 100, 
});
```
Valorar incluir este mecanismo que ya proporciona la librería que se utiliza.

2024-12-16 17:06 UTC, juanSTIC commented
Se han hecho pruebas incluyendo el parámetro connectTimeout en los tres puntos en los que se definen los parámetros de la conexión `mySqlConn` (líneas 27, 49 y 63), a pesar de que al usar el pool de conexiones solamente aplica el de la línea 27. En ninguno de los tres casos aplica el timeout. Por otro lado, no consigo encontrar en la documentación de mysql2 nada que indique que se puede usar este parámetro al crear el pool de conexiones.

2024-12-20 11:12 UTC, jortilles approved these changes
Visto y (A)problado

2025-01-20 11:41 UTC, AlbertoSTIC approved these changes
Aprobado

2025-01-21 08:15 UTC, merged