Eda syncro 20231019
SinergiaTIC/SinergiaDA pull request #28
Opened 2023-10-19 22:10 UTC by jortilles

Sincronización con EDA:
- Controles adicionales sobre columnas duplicadas. (Si hay columnas con el mismo nombre se sufijan con _1, _2, _3, etc)
- Opción panelMode en los dashboards  (https://edadoc.jortilles.com/#/publicos)
- Habilitada la opción de buscar usuarios en el panel de administración.
- Ampliada la barra de scroll

2023-10-23 12:01 UTC, juanSTIC requested changes
- En la funcionalidad del buscador de usuarios, aparece la palabra _Cercador_, independientemente del idioma que se esté usando. Debería ser una cadena traducida.

2023-10-23 12:03 UTC, juanSTIC commented
En el panelMode, hemos sustituido el enlace existente por el de SinergiaDataAnalitycs. En el commit https://github.com/SinergiaTIC/SinergiaDA/pull/28/commits/cd14369d970cf4d9dd91b9b5a567b988bd608276

2023-10-23 12:05 UTC, PaulaaSTIC commented
He estado haciendo pruebas intentando replicar "Controles adicionales sobre columnas duplicadas" y no he sido capaz. Los pasos que he seguido para que podais revisarlo son los siguientes:

1. He creado un informe y he incluido un panel.
2. En el panel he seleccionado "Editar consulta"
3. He seleccionado una entidad ("Campañas") y un atributo ("(n)Campañas")
4. Duplico el atributo, me aparece por defecto en el nombre del duplicado: "(n) Campañas (Copy)" .
5. Elimino el (Copy) selecciono Confirmar, y de nuevo Confirmar. 
6. Le doy a ejecutar y me saca una tabla con dos columnas "(n)Campañas".

En alguna de las pruebas que he realizado si que me ha puesto el _1, pero no en todas, creo que hay algo que no acaba de funcionar completamente.

2023-10-23 14:15 UTC, jortilles commented
Donde has hecho las pruebas? podemos revisar el log? Puede ser que una columna fuera  
"(n)Campañas" y la otra  
"(n)Campañas " con un espacio al final. Por lo que ya no son la misma columna?

2023-10-23 14:59 UTC, PaulaaSTIC commented
Nada, ya esta validado, el problema ha sido el espacio.

2023-10-25 12:57 UTC, juanSTIC approved these changes
He reemplazado el texto _Cercador_  , que se había quedado pendiente, de manera que en Español seguía viéndose mal (https://github.com/SinergiaTIC/SinergiaDA/pull/28/commits/b5c5ea00ebddb2044aaf896a2aa9a1c851b78db2).
Con esto queda aprobado.

2023-10-25 12:58 UTC, merged