Sda 26 solo aparecen agregaciones en campos de tipo numeric
SinergiaTIC/SinergiaDA pull request #30
Opened 2023-10-26 05:09 UTC by jortilles

Habilita la posibilidad de hacer agregaciones sobre campos numéricos.
HAY QUE HABILITAR ESA OPCIÓN EN EL MODELO. LOS CAMPOS TE TEXTO DEBEN TENER LAS AGREGACIONES POSIBLES DEFINIDAS ( normalmente count y count distinct )

2023-10-30 09:08 UTC, juanSTIC commented
Hemos definido las agregaciones en la tabla **sda_def_columns**, de manera que cada columna tiene informada correctamente las agregaciones que debe incluir:
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/34d5c13a-1d0f-48f9-a992-7761e5e2cc7d)
Sin embargo, después de ejecutar updateModel, el cambio no se ha trasladado al modelo.
Por lo que podemos ver en la fuente de datos, solo se mantiene la agregación _'none'_ 
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/36aa8bfa-b46f-4d90-ac38-6f4e9e32b4b1)
¿Hay algo que no estemos haciendo bien?

2023-10-30 10:48 UTC, asafJortilles commented
He subido una modificación en updateModel para que todas las columnas, independientemente del tipo, tengan las agregaciones. Confirmar si es correcta la funcionalidad. En local me está respondiendo correctamente.

2023-10-30 15:57 UTC, juanSTIC requested changes
A falta de una validación más detallada, hemos visto que las enumeraciones se muestran y se aplican correctamente en los campos de tipo `text` y `date`, sin embargo en los campos de tipo `enumeration`, a pesar de mostrarse, las agregaciones no aplican. 
Además de no aplicar en este caso, los campos e tipo `enumeration` directamente han dejado de funcionar, no mostrandose el valor del campo independientemente de que se use una agregación o no.

2023-11-08 05:47 UTC, jortilles commented
Esto ya se puede volver a validar

2023-11-14 15:14 UTC, juanSTIC approved these changes
En las pruebas realizadas se ha visto que el funcionamiento es correcto

2023-11-14 17:03 UTC, PaulaaSTIC approved these changes
(A)probado

2023-11-15 09:58 UTC, merged