SDA #60 - filtrado con valores no repetidos en desplegables de filtrado
SinergiaTIC/SinergiaDA pull request #34
Opened 2023-11-13 14:02 UTC by asafJortilles

Añadida discriminación por valores úncios en dropdowns de filtrado.

2023-11-14 14:55 UTC, juanSTIC requested changes
La funcionalidad no opera correctamente, se han visto al menos dos casos de uso, en los que se dan 2 errores diferente:
**Caso 1)** Se muestra un único valor en la  lista desplegable, aparentemente con la suma de todos los valores...
![valores1](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/40101a93-c56c-4c60-827d-fc1d2e948f62)

**Caso 2)** Se siguen mostrando los valores repetidos...
 
![valores2](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/1d1f8f29-dbc7-4d5f-a619-ab39e4f0ebff)

2023-11-14 16:01 UTC, asafJortilles commented
@juanSTIC Juan

Creo que en el caso 1, tienes apretado el botón de SUM en agregaciones. Te adjunto gif del comportamiento correcto sobre la  misma columna, sin la agregación.

![chrome-capture-2023-11-14](https://github.com/SinergiaTIC/SinergiaDA/assets/122270752/3d31d4bb-717d-4a69-8b8e-ec8bc0693578)

Para el caso 2, mando corrección en segundo commit.

2023-11-14 16:21 UTC, juanSTIC commented
> Creo que en el caso 1, tienes apretado el botón de SUM en agregaciones. Te adjunto gif del comportamiento correcto sobre la misma columna, sin la agregación.

Correcto, parece que el filtro funciona correctamente cuando está establecida la agregación en **No**, aunque no es muy  fino, esta parte la podemos considerar aceptable porque se resuelve el problema original y en todo caso,podemos modificar la Agregación y volver a poner _Suma_, depues de haber establecido el filtro.

2023-11-14 16:25 UTC, juanSTIC requested changes
Se ha visto que el filtro, aunque ahora funciona correctamente y muestra solo los valores distintos, estos aparecen desordenados, sin embargo en un mecanismo de selección  cabría esperar que aparezcan ordenados, en el caso de de los valores numéricos preferiblemente de menor a mayor. Si es razonablemente sencillo, deberíamos dejarlo fino.

2023-11-15 08:56 UTC, asafJortilles commented
Te refieres al desplegable en el diálogo de filtros, correcto?

2023-11-15 15:07 UTC, asafJortilles commented
He hecho la corrección del orden ascendente en los desplegables de los diálogos de columna y filtro.

2023-11-15 17:09 UTC, PaulaaSTIC approved these changes
(A)probado

2023-11-16 12:37 UTC, juanSTIC approved these changes
Visto y probado

2023-11-16 12:38 UTC, merged