Sda #129 enhancement mejorar el filtrado de informes y paneles a usuarios no administradores
SinergiaTIC/SinergiaDA pull request #37
Opened 2023-11-16 16:07 UTC by asafJortilles

Añadimos filtrado de paneles según permisos de usuario sobre tablas y columnas. 
También se añade el rescurso "Este panel no está disponible por falta de permisos" y algunas de sus traducciones (se hizo esta parte antes del issue de las traducciones)

2023-11-20 15:19 UTC, juanSTIC commented
¿Es exactamente esto lo que se ha implementado? https://github.com/SinergiaTIC/Sinergia-Data-Analytics/issues/129#issuecomment-1746577274

Por ahora según la pruebas realizadas no consigo hacerlo funcionar:
1. Creo un nuevo usuario no administrador (u1)
2. Mediante http://localhost:8080/es/#/data-source/111111111111111111111111 le doy al **usuario** permiso sobre la tabla personas. Hay varios informes que usan datos de módulo Personas
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/bbce5324-3347-4e78-b652-bf0859c88377)
3. Hago login con el usuario u1 y este no ve ningún informe.

2023-11-21 08:49 UTC, asafJortilles commented
Piensa que los permisos son sobre tablas y columnas. Si hay alguna columna
para la que el usuario no tiene visibilidad, no podrá ver el informe.

El lun, 20 nov 2023 a las 16:19, Juan Chamizo González (<
***@***.***>) escribió:

> ¿Es exactamente esto lo que se ha implementado? SinergiaTIC/Sinergia-Data-Analytics#129
> (comment)
> <https://github.com/SinergiaTIC/Sinergia-Data-Analytics/issues/129#issuecomment-1746577274>
>
> Por ahora según la pruebas realizadas no consigo hacerlo funcionar:
>
>    1. Creo un nuevo usuario no administrador (u1)
>    2. Mediante
>    http://localhost:8080/es/#/data-source/111111111111111111111111 le doy
>    al *usuario* permiso sobre la tabla personas. Hay varios informes que
>    usan datos de módulo Personas
>    [image: image]
>    <https://user-images.githubusercontent.com/46187267/284309965-bbce5324-3347-4e78-b652-bf0859c88377.png>
>    3. Hago login con el usuario u1 y este no ve ningún informe.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SinergiaTIC/SinergiaDA/pull/37#issuecomment-1819267796>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5E3IICS3VI3J53UYHCRJW3YFNYJVAVCNFSM6AAAAAA7OM7E7OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJZGI3DONZZGY>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-11-22 11:41 UTC, juanSTIC requested changes
Se ha vuelto a realizar la siguiente comprobación , que describe de manera más completa:
1. Creo un nuevo usuario no administrador (u1) y le añado al grupo SDA_BASIC
2. Mediante http://localhost:8080/es/#/data-source/111111111111111111111111 le doy al grupo SDA_BASIC permiso exclusivamente sobre la tabla Personas (sda_contacts). 
3. Creo un nuevo informe con un único panel que muestar información básica _exclusivamente_ de la tabla Pagos (sda_stic_payments).
4. En una nueva ventana de incognito, hago login con el nuevo usuario y compruebo que tiene acceso al informe recien creado, y al panel, cuando **no debería ver ni el informe ni el panel**

2024-02-26 22:07 UTC, jortilles commented
Este PR ya se puede volver a validar. 
Se ha comprobado que:
Un usuario puede ver un informe si ve al menos un panel del informe.
Si un usuario no puede ver un panel. Se le dice que no puede verlo por permisos.

2024-02-27 11:41 UTC, juanSTIC requested changes
No he conseguido ver ningún informe con un usuario no administrador. El usuario puede crear informes con sus módulos autorizados, pero al cargar la lista de informes siempre da el error que se muestra a continuación y no muestra ningún informe:

![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/4afb30a6-b66a-4723-ae6e-805f05cb693c)

2024-02-29 12:13 UTC, PaulaaSTIC requested changes
Si un usuario o grupo no tiene permisos sobre un panel de consulta SQL, este no se muestra, lo cual es correcto. Pero, en lugar del mensaje "Este panel no está disponible por falta de permisos", salta un `Server error`.

El mensaje de falta de permisos a veces no se lee bien porque no se ajusta al tamaño disponible. Una propuesta podría ser cambiar `<h2 text-align="center" style="position: absolute; top: 50%;"> `por la siguiente opción, que aparece en rojo y centrada: `<p class="alert alert-danger text-center" style="position: absolute; top: 50%; transform: translateY(-50%); font-size: 12px;">`.

2024-04-16 10:41 UTC, juanSTIC requested changes
Actualmente un usuario no administrador, no puede ver los informes públicos, incluso aunque estos informes los haya creado el mismo usuario y aunque contenga una consulta sobre tablas a las que si tiene acceso.

2024-04-17 04:42 UTC, jortilles commented
Lo vemos juntos. Porque a mi SI que me funciona correctamente.

2024-04-29 10:41 UTC, juanSTIC commented
> Lo vemos juntos. Porque a mi SI que me funciona correctamente.

Se verifico en reunión que no funciona y que un usuario no administrador, tras crear un informe y definirlo como público, deja de verlo automáticamente.

2024-05-08 09:58 UTC, jortilles commented
Esto ya se puede volver a validar. Los informes propios se ven siempre.

2024-05-10 09:05 UTC, jortilles commented
Hay que volver a revisar esto una vez aplicado el refactor de los grupos de seguridad.

2024-10-08 09:12 UTC, closed without merging

2024-10-08 09:12 UTC, jortilles commented
Lo cerramos administrativamente