SDA #82 - visión de la tabla seleccionada encima de columnas
SinergiaTIC/SinergiaDA pull request #43
Opened 2023-11-22 14:23 UTC by asafJortilles

Añadida la traducción al español del nuevo texto generado para visionar correctamente. Para añadir el resto de traducciones, utlizar el transunit i18n="atributsTitle+"

Hay también una eliminación de un console.log en panel-interaction-utils.ts, aprovechando el PR.

2023-11-23 13:20 UTC, juanSTIC requested changes
Aunque la apariencia es la acordada, se han visto diferentes errores que deben ser corregidor y revalidar completamente el PR.
- Se ha añadido documentación a la función de nueva creación

2023-11-23 13:20 UTC, juanSTIC commented on eda/eda_app/src/app/module/components/eda-panels/eda-blank-panel/eda-blank-panel.component.html
> +                                <h5>
El elemento eH5 está incluido dentro del elemento H4, lo cual es un error básico de HTML.
Teoricamente, si se corrige, no sería necesraio incluir la interpolación `{{getDisplayName(userSelectedTable)}}` en los ficheros de traducción. ¿no?

2023-11-23 13:20 UTC, juanSTIC commented on eda/eda_app/src/locale/messages.es.xlf
> +<trans-unit id="atributsTitle+" datatype="html">
Este elemento está contenido en medio de otro bloque trans-unit, lo cual es un error

2023-11-23 13:20 UTC, juanSTIC commented on eda/eda_app/src/locale/messages.es.xlf
> +       Columnas de:             {{getDisplayName(userSelectedTable)}}
Falta encerrar el valor original entre las etiquetas `<source></source>`

2023-11-23 13:20 UTC, juanSTIC commented on eda/eda_app/src/app/module/components/eda-panels/eda-blank-panel/eda-blank-panel.component.ts
> +
Se ha añadido un bloque con documentación de la función.

2023-11-23 13:20 UTC, juanSTIC commented on eda/eda_app/src/app/module/components/eda-panels/eda-blank-panel/eda-blank-panel.component.ts
> +    public getDisplayName(table) {
En la función no debería prevenirse/evitarse que se devuelva un valor undefined

2023-11-27 09:55 UTC, asafJortilles commented
He añadido estilos y la interpolación en el trans-unit. 
Para evitar el retorno de un valor undefined o nulo, por favor dime si queréis que retorne algún valor en concreto.

2023-11-29 16:46 UTC, juanSTIC commented
@asafJortilles He hecho algunos cambios y completado/corregido los ficheros de idiomas, revisalo por si crees que alguno de los cambios puede interferir en otra cosa. 
Los cambios están en https://github.com/SinergiaTIC/SinergiaDA/pull/43/commits/8fd2f9d12b9a2ea2ebf71e0247f73bcb389d212f

2023-11-29 16:47 UTC, juanSTIC approved these changes
Aprobado con los últimos cambios realizados

2023-11-30 12:53 UTC, PaulaaSTIC approved these changes
(A)probado

2023-11-30 15:24 UTC, merged