Eda syncro 20231221
SinergiaTIC/SinergiaDA pull request #74
Opened 2023-12-21 17:15 UTC by jortilles

## Descripción del Cambio
Mejoras:

Posibilidad de hacer un nuevo informe desde la barra lateral. siempre.
Mejora en la auditoría de accesos a los dashboards y los paneles.
Reorganización de las clases que realizan las consultas a bbdd
Posibilidad de tener campos calculados de texto. 
Corregido un bug en los campos calculados.
Actualización de puppeteer lo que permite subir a node.js 20
Corregidos los valores por defecto para las ordenacioens
Al cambiar una columna de panel no se reseteaban los filtos.
Mejora del algoritmo de ocultar repetidos.
Corrección de bug de permisos a nivel de columna.
Mejora en los filtros para los campos numericos.

## Issue(s) resuelto(s)
No resuelve ningún issue de Sinergiada

## Pruebas a realizar para validar el cambio

- Revisar las ejecuciones de los informes base y las consultas sql que se generan.

2024-01-17 11:07 UTC, juanSTIC requested changes
Pendiente de resolver conflictos

2024-01-17 12:57 UTC, jortilles commented
@juanSTIC  ya he resuelto el conflicto

2024-01-19 17:13 UTC, PaulaaSTIC commented on eda/eda_api/lib/services/query-builder/query-builder.service.ts
> +        console.log('Woho!!!!!!!!!');
Creo que esto se nos ha pasado.

2024-01-22 14:19 UTC, juanSTIC requested changes
Ver comentarios

2024-01-23 03:23 UTC, jortilles commented on eda/eda_api/lib/services/query-builder/query-builder.service.ts
> +        console.log('Woho!!!!!!!!!');
ES un trozo de código que está comentado. Está bien que esté ahi.  Forma parte de una comprobación.

2024-01-23 03:53 UTC, jortilles commented
He hecho tres commits en esta rama. 
1. Para poner los literales en minusculas. 
2. Para poner el puntero como una mano. No es en el archivo que apunta Juan. Es en otro. Pero se resuelve el issue que comenta.
3. He quitado el código comentado que señalaba Paula.

2024-01-23 09:30 UTC, juanSTIC approved these changes
Aprobado, con algún cambio añadido de carácter estético.

2024-01-23 09:59 UTC, merged