Hotfix - APP -  Problemas de visualización en gráficos de barras (normales y apiladas)
SinergiaTIC/SinergiaDA pull request #76
Opened 2024-01-15 15:36 UTC by jortilles

## Descripción del Cambio
Se añade espacio de gracia entre el final de las barras y el máximo del grafico en caso de que haya etiquetas. 
Adicionalmente se ha reformulado el número de lineas guia para que las barras ocupen el máximo posible del tamaño y se ha controlado la posición de la etiqueta para ponerla dentro de la barra en caso de que el gráfico sea muy pequeño

## Issue(s) resuelto(s)

- solves #83 

## Pruebas a realizar para validar el cambio
Ejecutar el grafico de barras con diferentes escalas de valores y tamaños de gráfico.

<img width="911" alt="image" src="https://github.com/SinergiaTIC/SinergiaDA/assets/1340212/dd748cb3-dc51-4603-bb5f-7c7eed5df674">

2024-01-16 12:42 UTC, PaulaaSTIC approved these changes
(A)probado

2024-01-18 08:22 UTC, juanSTIC approved these changes
Probado, ya se visualiza correctamente

2024-01-18 08:33 UTC, juanSTIC requested changes
Es necesario resolver los conflictos que se muestran, de manera que se mantengan los cambios propuestos, pero también se respeten el código existente, que permite que se muestren las eiquetas en los valores negativos, y que se introdujo en el PR #68

2024-01-24 14:53 UTC, PaulaaSTIC approved these changes

2024-01-24 17:40 UTC, juanSTIC approved these changes
Aprobado

2024-01-25 08:19 UTC, PaulaaSTIC approved these changes

2024-01-25 08:43 UTC, merged