Enhancemente - APP - Creación de página informativa
SinergiaTIC/SinergiaDA pull request #90
Opened 2024-01-29 12:48 UTC by juanSTIC

## Descripción del Cambio

## Issue(s) resuelto(s)

- solves 

## Pruebas a realizar para validar el cambio

## Información Adicional

2024-02-13 23:33 UTC, jalbaiges requested changes
Cadenas revisadas en los ficheros de _ca_, _en_ y _es_. Se puede copiar en _gl_ lo establecido en _es_.

Anoto algunos comentarios menores.

2024-02-13 23:33 UTC, jalbaiges commented on eda/eda_api/lib/router.ts
>  //Router para update model de SinergiaTIC
Comentario en castellano.

2024-02-13 23:33 UTC, jalbaiges commented on eda/eda_app/src/app/module/pages/about/about.component.html
> +              alt="Logotipo de Sinergia Data Analitycs"
Cadena a pasar a formato traducible.

2024-02-13 23:33 UTC, jalbaiges commented on eda/eda_app/src/locale/stic_messages.ca.xlf
No sé si es relevante, pero tanto este fichero como el de gallego no tiene el código de idioma correcto en la línea 4.

2024-02-15 11:04 UTC, juanSTIC commented on eda/eda_app/src/locale/stic_messages.ca.xlf
Diría que muy relevante no es, pero si incorrecto, así que lo dejaremos bien...

2024-02-15 11:06 UTC, juanSTIC commented on eda/eda_app/src/app/module/pages/about/about.component.html
> +              alt="Logotipo de Sinergia Data Analitycs"
Traducido

2024-02-15 11:09 UTC, juanSTIC commented on eda/eda_api/lib/router.ts
>  //Router para update model de SinergiaTIC
Traducido a Inglés, aunque hay una mezcla de idiomas en los comentarios, la idea es ir pasandolos al Inglés

2024-02-15 11:14 UTC, juanSTIC commented
> Cadenas revisadas en los ficheros de _ca_, _en_ y _es_. Se puede copiar en _gl_ lo establecido en _es_.
> 
> Anoto algunos comentarios menores.

Debido a la dificultad de usar contenidos HTML dentro de las traducciones, (en teoría es posible,  pero en la práctica no ha funcionado correctamente), y dado que el único punto de SDA/EDA en que se da esta situación es en la página informativa que se incluye en este PR, se ha optado por incluir las traducciones directamente en el código, de manera que mediante la detección del idioma se muestra solo el texto correspondiente.

2024-02-15 11:22 UTC, jalbaiges submitted a review, later dismissed

2024-02-19 15:05 UTC, jortilles approved these changes

2024-02-20 09:01 UTC, PaulaaSTIC approved these changes
(A)probado

2024-02-20 10:13 UTC, merged