Improvement - APP - Habilitar filtros no editables/no visibles a nivel de informe - SDA59 #97
SinergiaTIC/SinergiaDA pull request #98
Opened 2024-02-04 08:24 UTC by jortilles

## Descripción del Cambio

Se ha añadido la posibilidad de definir un filtro público,  deshabilitado y oculto.  Se ha añadido un control para que el usuario anónimo no pueda cambiar la configuración de los informes. Para los informes compartidos con cualquier usuario está el control "Edición Privada" que proporciona control sobre esto.

## Issue(s) resuelto(s)
- solves https://github.com/SinergiaTIC/SinergiaDA/issues/59 

## Pruebas a realizar para validar el cambio
Crear un informe poniendo un filtro oculto, uno deshabilitado y uno público.
1. Comprobar que todos los filtros estan disponibles para el usuairo que los creó y los admins.
2. Comprobar que los filtros tienen la visibilidad correcta para el resto de usuarios.
2.1 Comprobar que el resto de usuarios pueden modificar la visibilidad de los filtros públicos.
2.2 Comprobar que el resto de usuarios no pueden modificar los filtros si yo marco la opicón "edición privada"
3. Comprobar el correcto funcionamiento con el usuario anónimo
3.1 Comprobar que el usuario anónimo no puede editar la configuración de los filtros.

## Información Adicional

Se ha hecho un nuevo pull request con los cambios de últma hora.

2024-02-05 07:55 UTC, juanSTIC requested changes
A falta de una revisión más completa, se ha visto un error que es necesario modificar:A falta de una revisisón más completa se ha visto un error que es necesario modificar:
Cuando un administrador **vuelve a editar** un filtro guardado como _deshabilitado_ u _oculto_, el filtro establece su estado directamente a _público_ y no al que se hubiera indicado cuando se guardo. Esto provocará confusión entre usuarios y derivará en que algunos filtros se perderán al no darte cuenta de que se ha _restablecido_ el estado.

2024-02-05 15:47 UTC, asafJortilles commented
@juanSTIC corrección ya disponible

2024-02-06 16:55 UTC, juanSTIC approved these changes
*A tener en cuenta a nivel de documentación.* 
Se produce un efecto extraño si se establece un filtro de Solo Lectura, por ejemplo en el campo Género y despues se incluye un _Gráfico de pastel_ para el mismo campo, lo que permite al usuario no administrador del informe aplicar un nuevo filtro sobre las dimensiones que se muestran en el propio gráfico, llegando incluso a poder guardarlo y a _sobreescribir_ el filtro que se ha definido como  de Solo lectura.

Por lo demas la funcionalidad es correcta

2024-02-06 16:55 UTC, juanSTIC reviewed
*A tener en cuenta a nivel de documentación.* 
Se produce un efecto extraño si se establece un filtro de Solo Lectura, por ejemplo en el campo Género y despues se incluye un _Gráfico de pastel_ para el mismo campo, lo que permite al usuario no administrador del informe aplicar un nuevo filtro sobre las dimensiones que se muestran en el propio gráfico, llegando incluso a poder guardarlo y a _sobreescribir_ el filtro que se ha definido como  de Solo lectura.

Por lo demás la funcionalidad es correcta

2024-02-06 16:55 UTC, juanSTIC reviewed
*A tener en cuenta a nivel de documentación.* 
Se produce un efecto extraño si se establece un filtro de Solo Lectura, por ejemplo en el campo Género y despues se incluye un _Gráfico de pastel_ para el mismo campo, lo que permite al usuario no administrador del informe aplicar un nuevo filtro sobre las dimensiones que se muestran en el propio gráfico, llegando incluso a poder guardarlo y a _sobreescribir_ el filtro que se ha definido como  de Solo lectura.

Por lo demás la funcionalidad es correcta

2024-02-07 10:10 UTC, juanSTIC requested changes
Verificar la compatibilidad con los filtros de gráficos de pastel. 
El problema es que un administrador, clickando en un gráfico, puede agregar un filtro previamente existente

2024-03-09 08:43 UTC, jortilles commented
He hecho los ajustes finales para que funcione perfecto.

Sabemos que si tienes un filtro oculto y hacles click en el grafico de pastel pasa un comportamiento inesperado. Pero eso formará parte del pr  https://github.com/SinergiaTIC/SinergiaDA/pull/120 

Ya se puede validar esta funcionalidad

2024-03-11 15:20 UTC, juanSTIC submitted a review, later dismissed
Funcionamiento correcto a falta de solucionar el bug relativo a los filtros que se añaden al hacer click sobre los gráficos de pastel

2024-03-11 16:47 UTC, PaulaaSTIC submitted a review, later dismissed
(A)probado

2024-03-11 22:54 UTC, jalbaiges approved these changes
Cadenas revisadas. Aprovechando que estaba incluido en el PR se ha revisado también un 60% del fichero messages.ca.xlf. Sería deseable llevarlo a EDA. Por cierto, ¿por qué las cadenas nuevas de este PR aparecen por duplicado tanto en messages como en stic_messages si tienen el mismo contenido?

2024-03-13 06:37 UTC, juanSTIC approved these changes
Reaprobado

2024-03-13 06:37 UTC, merged