Hotfix - API - No funciona el filtro de valores no nulos dentro de un campo en un panel - Sda#56
SinergiaTIC/SinergiaDA pull request #99
Opened 2024-02-04 08:57 UTC by jortilles

## Descripción del Cambio
Cuando se añaden varios filtros diferentes sobre una columna EDA presupone que se quiere hacer un or. Por ejemplo para dos rangos de tiempo. Pero en el caso de que queramos filtrar una serie de valores y el valor nulo esta lógica es incorrecta puesto que para poder filtrar el valor nulo se tiene que hacer especificamente. Por lo que necesariamente tendremos que hacer dos filtros. Los valores que quermos filtrar y el nulo.

## Issue(s) resuelto(s)
- solves  https://github.com/SinergiaTIC/SinergiaDA/issues/56

## Pruebas a realizar para validar el cambio
Hacer un informe con varios filtros sobre una misma columna
Hacer un iforme con varios filtros sobre una columna. Uno de los cuales debe ser el valor nulo.

2024-02-19 10:48 UTC, PaulaaSTIC requested changes
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/11f5d5da-1469-4660-97c9-7d7dea87099e)
Realizando pruebas, sin utilizar filtros se ha visto que los valores vacíos cogen el valor de la fila superior. Al probar la siguiente consulta, se verá que Almería tendrá el valor de 15.
```
SELECT provincia, valor
FROM (
  SELECT 'Albacete' AS provincia, 10 AS valor
  UNION ALL
  SELECT 'Alicante', 15
  UNION ALL
  SELECT 'Almería', 0
  UNION ALL
  SELECT 'Zamora', 5
  UNION ALL
  SELECT 'Zaragoza', 8
) AS t;
```
Probando en `reporting` la misma consulta si que devuelve un 0.

**Actualizado**: había que realizar merge con reporting

2024-02-19 15:09 UTC, PaulaaSTIC requested changes
- Si configuramos el tipo de filtro como "valores no nulos", se mostrarán todos los valores, incluidos nulos.
- Si configuramos el tipo de filtro como "No igual a" y seleccionamos vacío, no se mostrarán los registros que estén vacíos, pero sí los que contengan otros valores.
- Si establecemos "No igual a Femenino" y otro filtro "No igual a" con cualquier otro valor (masculino, otros o vacío), se mostrarán todos los registros, incluidos los masculinos, femeninos, nulos y otros. Las dos condiciones se separan por un `OR` lo que hace que no funcione correctamente, debería funcionar con un `AND`.
```
where  (`sda_l_contacts_stic_gender_c_stic_genders_list`.`value`  <> 'Femenino'  
  or `sda_l_contacts_stic_gender_c_stic_genders_list`.`value`  <> 'Masculino'  
 )  

```

2024-03-13 10:33 UTC, juanSTIC commented
integrado en #120

2024-03-13 10:55 UTC, jortilles commented
Se integra en https://github.com/SinergiaTIC/SinergiaDA/pull/120

2024-03-13 10:55 UTC, closed without merging